Fixed issue with pg SSL
getferdi/server pull request #33
Opened 2020-07-15 13:15 UTC by Omkaragrawal

I added a DB_SSL variable to control the SSL behaviour for Postgres specifically. 
Resolving #32  #6 #7

2020-07-19 18:42 UTC, vantezzen commented
Thank you for your contribution! It looks like you duplicated most database settings in `.env.example`. Could you please restore the just the old settings and add your `DB_SSL` setting to end of the existing list?

2020-07-22 17:36 UTC, vantezzen commented
Could you please instead add this to the documentation in the `README.md`? Otherwise this might be confusing for new users as to why there are two database configurations in the file.

2020-07-24 20:54 UTC, Omkaragrawal commented
> Could you please instead add this to the documentation in the `README.md`? Otherwise this might be confusing for new users as to why there are two database configurations in the file.

Hey I have made changes. Please review it.

2020-10-09 01:10 UTC, Omkaragrawal commented
Hy  @vantezzen ,
I have resolved the conflict, please accept the changes. 
Also I request you to add a "Hacktoberfest-accepted" label to this PR, if you could then this would help me in completing my Hacktoberfest target.

2020-10-10 12:38 UTC, vantezzen requested changes
Thank you for your contribution. Could you please commit the suggestion I added below so we don't break any existing configuration.

Regarding Hacktoberfest: As far as I can tell, this PR will not count towards your Hacktoberfest PRs as it was created before 1st October. If you want to, you can close this PR and open a new one with these changes in order to let them count.

2020-10-10 12:38 UTC, vantezzen commented on config/mail.js
> +    secure: JSON.parse(Env.get("MAIL_SSL", "true")),
```suggestion
    secure: JSON.parse(Env.get("MAIL_SSL", Env.get('SSL', false))),
```

2020-10-10 19:52 UTC, Omkaragrawal commented on config/mail.js
> +    secure: JSON.parse(Env.get("MAIL_SSL", "true")),
Hey,
Thanks for allowing me to create a new PR for hacktoberfest, anyways I'll continue with this PR as it would seem inappropriate 😅.

Besides, I made it MAIL_SSL because it would be more clear as to what SSL it is, as you can see, I have added a SSL option for DB too, so I would recommend to make it MAIL_SSL instead of just SSL. It makes everything clear specially for the ones who haven't looked inside the code.

2020-10-11 08:47 UTC, vantezzen commented on config/mail.js
> +    secure: JSON.parse(Env.get("MAIL_SSL", "true")),
Yes, I understand that decision. Your changes to change the name of the variable would break existing configurations though (including ours).

That is why I added `SSL` as an "alias" to `MAIL_SSL`: It will first try to use `MAIL_SSL`, if that doesn't exist then it will search for just `SSL` and if both of those don't exist it will fallback to the default value `false` which is also the current default value.

We try to keep updating ferdi-server as easy as possible so we don't want to just introduce a breaking change like this from one commit to the other.

2020-10-15 12:27 UTC, Omkaragrawal commented
Hey, @vantezzen  I have made changes as per your suggestions.

2020-10-15 16:16 UTC, vantezzen approved these changes

2020-10-15 16:17 UTC, vantezzen commented
Thank you for your contribution and for taking my feedback into account!

2020-10-15 16:17 UTC, merged

2021-12-23 18:40 UTC, kytwb commented
@all-contributors please add @Omkaragrawal for code