Moving the server-docker repository to the server repository and enabling image building from the current version of the application code
getferdi/server pull request #48
Opened 2021-02-05 19:55 UTC by k0staa

Hello everyone.
I would like to support the server and front-end parts of the project with my work because I use ferdi in daily basis and I really love the project. You've really done a great job 🙂
I saw a discussion (@kytwb ) about moving the `server-docker` repository to `server` repository in [https://github.com/getferdi/server/pull/11](https://github.com/getferdi/server/pull/11) and [https://github.com/getferdi/server/issues/5](https://github.com/getferdi/server/issues/5) and it seems to me to be absolutely justified. I would like to be able to build a docker image on top of the current application code (now a packed master version is downloaded during building process)

Changes that I would like to propose in the current pull request:

- deleting the `getferdi/server-docker` repository and moving its contents to the `docker` directory in the `getferdi/server` repository
- build an image using the current code. A copy of the repository files will be used to run ferdi server in docker image.
- add sample `docker-compose.yml` file
- update of all README files

The configuration is similar to the one used e.g. here [https://github.com/matrix-org/synapse](https://github.com/matrix-org/synapse)

I know that @xthursdayx mention some concerns about whether it would be possible to configure Docker Hub's automated cloud builder with `Dockerfile` in a separate directory but this should be possible. According to the [https://docs.docker.com/docker-hub/builds/#set-up-build-rules](https://docs.docker.com/docker-hub/builds/#set-up-build-rules) documentation,  the location of the `Dockerfile` should be set up in the `Build rules section`

2021-02-05 21:39 UTC, xthursdayx commented
Thanks for your work on this @k0staa ! In general I'm supportive of the idea of merging the ferdi server docker image into the main ferdi server repo for the sake of simplicity. After a quick glance through your PR, I don't see any problems or reasons not to move forward with merge. 

One thing to note though is that I think these issues should be addressed during the process of merging the two repos: 
https://github.com/getferdi/server/issues/45
https://github.com/getferdi/server/pull/46
https://github.com/getferdi/server/pull/47
https://github.com/getferdi/server/pull/42
https://github.com/getferdi/server-docker/issues/8


However, there does seem to be an issue with the [ferdi-server repo on Docker Hub](https://hub.docker.com/repository/docker/getferdi/ferdi-server). For some reason, under the `Builds` configuration menu there is an message that says "YOUR REPOSITORY IS NO LONGER AVAILABLE. PLEASE SELECT A REPOSITORY TO CONTINUE." But Docker Hub won't let me update the server-docker repo build source to `getferdi/server` or even set it to the original `getferdi/server-docker` source repo. The only repos it is showing me as options are `ferdi`, `nightlies`, `recipes`, `website`, and `wiki`. 

I don't know why this is happening, but I'm wondering if it is a permission issue. I am still listed as an `owner` on the Ferdi organization on Docker Hub, so the problem likely isn't there.  I have write access for the `getferdi/server-docker` repo, so I don't know why it isn't showing up as an option on Docker Hub. @kytwb or @vantezzen , can you give me write access for the  `getferdi/server` repo so that I can work on integrating the docker code into the main server repo? Once that is sorted out I will look into updating Docker Hub for the newly merged server repo. Cheers.

2021-02-06 10:54 UTC, k0staa commented
Thanks @xthursdayx . I will be happy to help you with the topics you mentioned.
If [https://github.com/getferdi/server/pull/47](https://github.com/getferdi/server/pull/47) could be merged, this would open possiblity to merge [https://github.com/getferdi/server-docker/pull/9](https://github.com/getferdi/server-docker/pull/9) which will resolve issue [https://github.com/getferdi/server-docker/issues/8](https://github.com/getferdi/server-docker/issues/8) on which I also agree :smiley:. Then I can help with moving [https://github.com/getferdi/server-docker/pull/9](https://github.com/getferdi/server-docker/pull/9) to the docker configuration in the `getferdi/server` repository. If it gets merged before this pull reuqest is merged then I can add that to it.
I suspect there should be no problem with [https://github.com/getferdi/server/pull/42](https://github.com/getferdi/server/pull/42).
As for issue [https://github.com/getferdi/server/issues/45](https://github.com/getferdi/server/issues/45) and draft pull request to it -> [https://github.com/getferdi/server/pull/46](https://github.com/getferdi/server/pull/46), I saw that @cromefire mention that it should probably wait for auth to be fully compatible with adonis v5 but maybe it's worth to consider merging it if it's working with  "@adonisjs/auth": "^5.1.1" ?.

2021-02-06 11:08 UTC, cromefire commented
Auth doesn't support jwt yet, which is required, which leaves it in a non-functional state

2021-02-06 11:13 UTC, cromefire commented
> so someone with more familiarity with AdonisJS will need to address these issues

Well I basically don't know it myself, but upgrading is relatively straight forward. It's basically mostly rewriting imports and js to ts (which I've done a few times) so that mostly works out fine.

2021-02-06 12:00 UTC, kytwb commented
@k0staa thank you for the initiative!

@xthursdayx I have granted you write access to the repository.

> More importantly though, there seems to be an issue with the ferdi-server repo on Docker Hub. For some reason, under the Builds configuration menu there is an message that says "YOUR REPOSITORY IS NO LONGER AVAILABLE. PLEASE SELECT A REPOSITORY TO CONTINUE." But Docker Hub won't let me update the server-docker repo build source to getferdi/server or even set it back to the original getferdi/server-docker source repo. The only repos it is showing me as options are ferdi, nightlies, recipes, website, and wiki.

I'm also seeing the error at https://hub.docker.com/repository/docker/getferdi/ferdi-server/builds/edit:

<img width="1283" alt="Screen Shot 2021-02-06 at 12 41 47 PM" src="https://user-images.githubusercontent.com/412895/107117175-b0697e80-6878-11eb-917c-136f8c94e1da.png">

It seems similar to https://github.com/docker/hub-feedback/issues/1995.

2021-02-06 13:21 UTC, cromefire commented
Maybe it would make sense to close this for now and recreate it with the dockerfile from getferdi/server-docker#9 ? I'd be happy to do that. That docker files is also a lot smaller (in terms of source and requirements), so it might make more sense to move that.

2021-02-06 13:28 UTC, cromefire commented
> I'm also seeing the error at https://hub.docker.com/repository/docker/getferdi/ferdi-server/builds/edit:

Maybe it'd be wise in the meantime to at least use some other means of building docker images, for example by some external CI like gitlab (gitlab is one where I can help, because I use it a lot + it allows vulnerability scanning for containers/code if wanted)

2021-02-06 15:11 UTC, k0staa commented
> Maybe it would make sense to close this for now and recreate it with the dockerfile from [getferdi/server-docker#9](https://github.com/getferdi/server-docker/pull/9) ? I'd be happy to do that. That docker files is also a lot smaller (in terms of source and requirements), so it might make more sense to move that.

If you will finish it and merge, I can add your changes to this pull request. I will only change the part that download (curl) the packed application to a similar solution that I did in this pull request.

2021-02-06 17:51 UTC, cromefire commented
Marked it as mergable, you can basically remove the `docker` folder as you only need the `docker-compose.yaml` file, the `Dockerfile`, and `entrypoint.sh`. I'd maybe just add a `docs` folder and then put most of the old `README.md` at `docs/docker.md`

2021-02-06 17:53 UTC, cromefire commented
I think you basically need to change line 7 - 9 to:
```dockerfile
RUN ["apk", "add", "--no-cache", "python", "make", "gcc", "g++", "libc-dev", "sqlite-dev"]

COPY . /code
```

2021-02-06 18:00 UTC, cromefire commented
That structure is basically already a preperation the new adonis version where it just outputs all files needed to a `build` directory or something so you could also think about building the app outside of the container so you don't have to do it twice for example.

2021-02-06 18:05 UTC, cromefire commented
I also think the thing with the database volume in the docker compose file doesn't work well because there is also some code in that directory, but now we are able to set a data dir accordingly to change that (see #47)

2021-02-06 18:32 UTC, k0staa commented
@cromefire thanks for the quick response :+1:
> Marked it as mergable, you can basically remove the `docker` folder as you only need the `docker-compose.yaml` file, the `Dockerfile`, and `entrypoint.sh`. I'd maybe just add a `docs` folder and then put most of the old `README.md` at `docs/docker.md`

I personally think that I prefer to have this files in separate directory (`docker`) ,especially if there is also `entrypoint.sh`but if anyone else has the same opinion, I can do that ofc.

> Also don't remove `curl` from line 23 and 28, it's used for the healthcheck.

Sure, no worries :wink:

>I also think the thing with the database volume in the docker compose file doesn't work well because there is also some code in that directory, but now we are able to set a data dir accordingly to change that (see #47, so basically set DATA_DIR=data in compose and then you can use the volume /app/data)

Thanks, I think that I could use `DATA_DIR` env and change volumes accordingly :+1:

2021-02-06 18:48 UTC, cromefire commented
> I personally think that I prefer to have this files in separate directory (docker) ,especially if there is also entrypoint.shbut if anyone else has the same opinion, I can do that ofc.

I'd at least put the `Dockerfile` at the root because of the build context and stuff I don't have a particular opinion about the rest

2021-02-07 11:51 UTC, k0staa commented
I just pushed some changes:
 - merge upstream/master to my pull request branch 
 - add and adjust @cromefire changes to docker configuration [https://github.com/getferdi/server-docker/pull/9](https://github.com/getferdi/server-docker/pull/9)
 - fix issue with generating or using existing APP_KEY (please look at `entrypoint.sh` and `Dockerfile`)
 - last commit change behaviour of choosing DATA_DIR. We used  `Helpers.appRoot` but I recon that we can use any system folder to be used as database storage ? 
 - `docker-compose.yml` - added DATA_DIR example usage

2021-02-07 11:53 UTC, cromefire commented on docker/entrypoint.sh
> +export APP_KEY=$APP_KEY
```suggestion
export APP_KEY
```
Should be sufficient

2021-02-07 11:54 UTC, cromefire commented
> last commit change behaviour of choosing DATA_DIR. We used Helpers.appRoot but I recon that we can use any system folder to be used as database storage ?

It's harder to not do that without breaking stuff, the Adonis upgrade will improve on that

2021-02-07 11:56 UTC, cromefire requested changes

2021-02-07 11:56 UTC, cromefire commented on config/database.js
> +      filename: `${Env.get('DATA_DIR', 'database')}/${Env.get('DB_DATABASE', 'development')}.sqlite`,
I suggest leaving this for now and improving it when we add breaking changes anyway

2021-02-07 12:00 UTC, cromefire requested changes

2021-02-07 12:00 UTC, cromefire commented on docker/Dockerfile
> +COPY . /server-build
I'd move it to the top level because people expect `docker build .` and not something like `docker build -f docker/Dockerfile .`

2021-02-07 12:16 UTC, k0staa commented on config/database.js
> +      filename: `${Env.get('DATA_DIR', 'database')}/${Env.get('DB_DATABASE', 'development')}.sqlite`,
You right, I didn't think of it that way...
From my perspective, someone who updates the server will simply have to set a variable, but in fact it must be treated as breaking change. On the other hand, the possibilities of using `DATA_DIR` decrease by this ... 
I will revert that and maybe add some info to README

2021-02-07 12:17 UTC, k0staa commented on docker/entrypoint.sh
> +export APP_KEY=$APP_KEY
Sure, thanks. I will fix that :+1:

2021-02-07 12:18 UTC, cromefire commented on config/database.js
> +      filename: `${Env.get('DATA_DIR', 'database')}/${Env.get('DB_DATABASE', 'development')}.sqlite`,
My idea ist: let's get this working first, then take the time, redesign badly designed things and then do 1 full major breaking change

2021-02-07 12:23 UTC, k0staa commented on docker/Dockerfile
> +COPY . /server-build
Ok, imho there are different approaches to this and probably 50% of projects have that on root and other 50% in some directory but I won't argue and I'll change :+1:

2021-02-07 15:28 UTC, k0staa commented
@cromefire I fixed everything you mention [https://github.com/getferdi/server/pull/48/commits/02000d89159ba171cabbd341139871236f3df386](https://github.com/getferdi/server/pull/48/commits/02000d89159ba171cabbd341139871236f3df386)

But there is also one more topic. In order not to add breaking changes, I added a script that will read `config.txt` because some users may be used to using the image without specifying certain parameters. I did not add the script to save new envs because I think this should be abandoned in favor of using ENV parameters or just editing `config.txt` . I've added instructions in README.md

Changes in the code regarding this part -> [https://github.com/getferdi/server/pull/48/commits/bbd2132feede2d8c5e214c4d8a436f5505b9a766](https://github.com/getferdi/server/pull/48/commits/bbd2132feede2d8c5e214c4d8a436f5505b9a766)

2021-02-07 15:34 UTC, cromefire commented on .env.example
> +DATA_DIR=database
This is an example so it doesn't need to be compatible

2021-02-07 15:34 UTC, cromefire commented on docker/README.md
> +| `-e DATA_DIR=database` | for specifying sql-lite database folder, default is database. Currently you need to use folder inside `/app` directory |
Same no need for compatibility in the recommendation

2021-02-07 15:34 UTC, cromefire commented on docker/README.md
> +	docker create \
Maybe add `-e DATA_DIR=data here? (See above)

2021-02-07 15:34 UTC, cromefire commented on docker/docker-compose.yml
> +      - DATA_DIR=my-database
Maybe use ab common folder across all examples, like `data` or so? (Results in a nice folder: `/app/data`)

2021-02-07 18:06 UTC, cromefire requested changes

2021-02-07 18:06 UTC, cromefire commented on docker/entrypoint.sh
> +	cp /app/.env.example /config/config.txt
That'll make the app unusable, because the .env just overwrites everything. I'd just read the file if it exists and you're good to go

2021-02-07 18:08 UTC, cromefire commented on docker/entrypoint.sh
> +	cp /app/.env.example /config/config.txt
I'd eventually like to even deprecate that method, because there are better ways, like .env files with docker-compose.

2021-02-07 22:09 UTC, xthursdayx commented on docker/entrypoint.sh
> +	cp /app/.env.example /config/config.txt
The only issue with that is that not everyone uses docker-compose. I initially built the Docker container to run on Unraid, which uses its own "DockerMan" system. Either way, I'd be wary of a solution that relies soley on docker-compose.

2021-02-07 22:47 UTC, cromefire commented on docker/entrypoint.sh
> +	cp /app/.env.example /config/config.txt
But all those solutions basically provide some more comfortable way, only normal docker is a bit clumsy, because you have to pass the env via command line and even that isn't too bad (I mean many if not most containers only provide environment variables)

2021-02-07 22:51 UTC, cromefire commented on docker/entrypoint.sh
> +	cp /app/.env.example /config/config.txt
Even docker cli supports .env files: https://docs.docker.com/engine/reference/commandline/run/
I can find an appropriate screenshot for dockerman quickly, but is looks like it also has a nice page to configure env variables, so that also not a problem.

2021-02-07 22:52 UTC, cromefire commented on docker/entrypoint.sh
> +	cp /app/.env.example /config/config.txt
So docker-compose is only an example, but this works well in basically any environment I know of.

2021-02-08 13:09 UTC, k0staa commented on docker/entrypoint.sh
> +	cp /app/.env.example /config/config.txt
I know all the pros and cons. I was aware of them. If we throw this part away, of course `config.txt` will be useless from now on. The question is whether it is breaking change or not?

>That'll make the container unusable

 why ? It may not be super clear:
- old `config.txt` exisitng , we use it, environment variables sent to the container override it
- there is no `config.txt`, we create a default, environmental variables sent to the container override it

but it will work for users who don't use `.env` or send any environment variables.
(I personally would prefer to delete it :smile: )

2021-02-08 13:20 UTC, cromefire commented on docker/entrypoint.sh
> +	cp /app/.env.example /config/config.txt
Yes it would be breaking so for now there's on deprecation if we choose to do it

> there is no `config.txt`, we create a default, environmental variables sent to the container override it

The default disables any use of variables, because the config ranks higher an therefore you cannot override the defaults.

For now If just read it if it's there for compatibility and otherwise leave it alone.

2021-02-08 13:22 UTC, cromefire commented on docker/entrypoint.sh
> +	cp /app/.env.example /config/config.txt
That's why I added the `touch .env`

2021-02-08 13:47 UTC, k0staa commented on docker/entrypoint.sh
> +	cp /app/.env.example /config/config.txt
> The default disables any use of variables, because the config ranks higher and therefore you cannot override the defaults.

If you mean that the values in it stay the default then YES. It's just READ_ONLY from now on (that was the intention)

Of course, the container  envs are superior. It can be easily tested. Steps:
1. Remove volumes (config)
2. In `docker-compose.yml` change `IS_REGISTRATION_ENABLED` value to `false`
3. Run the server and ferdi app
4. Try to register new user

Default value for ` IS_REGISTRATION_ENABLED` is `true` but container ENV override it. 

So, In a way it's deprecation and I understand we can leave it like that ?

2021-02-08 14:22 UTC, cromefire commented on docker/entrypoint.sh
> +	cp /app/.env.example /config/config.txt
Maybe I had some flaws in my testing or this changed with the new version of Adonis, but in my tests I could not override the .env files.

2021-02-08 14:22 UTC, cromefire commented on docker/entrypoint.sh
> +	cp /app/.env.example /config/config.txt
Depreciation would probably be mostly in the realm of documentation.

2021-02-08 16:49 UTC, k0staa commented on .env.example
> +DATA_DIR=database
This file is copied as default `config.txt` if there is none ,so I would leave `database` here (that was always default value)

2021-02-08 16:54 UTC, cromefire commented on .env.example
> +DATA_DIR=database
This of course depends whether you want to deprecate the config I wouldn't copy it in both cases but especially if we'd want to deprecate it you probably shouldn't copy it, I'd rather invest more into a better documentation which still seems improvable.

2021-02-08 17:00 UTC, cromefire commented on docker/entrypoint.sh
> +	cp /app/.env.example /config/config.txt
So we should decide whether we'd want to deprecate that way, if I'd just not create a config file if not already there (which I, personally, am no fan of anyway). That way we're sure or otherwise I'll have to test it again

2021-02-08 17:06 UTC, k0staa commented on docker/entrypoint.sh
> +	cp /app/.env.example /config/config.txt
>Maybe I had some flaws in my testing or this changed with the new version of Adonis, but in my tests I could not override the .env files.

I do not fully understand. If you use the `.env` file in the directory where you run docker-compose then these variables will be taken first. If you send some variables to the container and in the container those from `config.txt` are taken anyway, I don't have such a problem and maybe we will need a third person to check it.

2021-02-08 17:40 UTC, cromefire commented on docker/entrypoint.sh
> +	cp /app/.env.example /config/config.txt
Nah I'll test again, I didn't test it inside docker at all, saw that while upgrading Adonis

2021-02-09 12:16 UTC, k0staa commented on .env.example
> +DATA_DIR=database
Ok, I will remove that value and I will add some info in readme which will describe that `config.txt` is used but it's not uppdated anymore and will be removed in future realeases in favor of using environment variables.

2021-02-09 12:40 UTC, cromefire commented on .env.example
> +DATA_DIR=database
Sounds good

2021-02-09 16:05 UTC, cromefire commented on docker/entrypoint.sh
> +	cp /app/.env.example /config/config.txt
> Maybe I had some flaws in my testing or this changed with the new version of Adonis, but in my tests I could not override the .env files.

I retestet and it does overwrite the `.env`.

2021-02-09 16:28 UTC, cromefire reviewed
Added a bunch of suggestions to improve a lot of small stuff

2021-02-09 16:28 UTC, cromefire commented on docker/README.md
> +If any environmental parameter is not passed to the container, its value will be taken from the `config.txt` file. You can also edit the `config.txt` file, but it is advisable to send the environment
Maybe remove it from here or add a deprecation notice?

2021-02-09 16:28 UTC, cromefire commented on docker/entrypoint.sh
> +	cp /app/.env.example /config/config.txt
So I think we can safely remove this line

2021-02-09 16:28 UTC, cromefire commented on docker/entrypoint.sh
> +fi
I'd just change this to:
```suggestion
if [ -f /config/config.txt ]; then
    cp /config/config.txt /app/.env
else
    cp /app/.env.example /app/.env
fi
```

Because we are read-only anyway.

2021-02-09 16:28 UTC, cromefire commented on docker/README.md
> +* **25.09.19:** - Initial Release.
I think this can also go away, if we want to release real tagged versions?

2021-02-09 16:28 UTC, cromefire commented on docker/README.md
> +- `Recipe files`: Recipe files that you created using the [Franz recipe creation guide](https://github.com/meetfranz/plugins/blob/master/docs/integration.md). Please do *not* package your files befor
I also think this might be not the right, place but maybe something to fix after this PR

2021-02-09 16:28 UTC, cromefire commented on docker/README.md
> +| Ethereal | A disposable account is created automatically if you choose this option. |
The new adonis version doesn't support this anymore, so maybe we should add a deprecation notice here?

2021-02-09 16:28 UTC, cromefire commented on docker/README.md
> +| MySQL | mysql |
```suggestion
| MariaDB/MySQL | mysql |
```

2021-02-09 16:28 UTC, cromefire commented on docker/README.md
> +The docker can be run as is, with the default sqlite database, or you can modifying your ENV variables to use an external database (e.g. MYSql, MariaDB, Postgres, etc). After setting up the docker co
```suggestion
The docker can be run as is, with the default sqlite database, or you can modify your environment variables to use an external database (e.g. MySQL, MariaDB, Postgres, etc). After setting up the docker container you will likely need to create a reverse proxy to access Ferdi-server outside of your home network, using for example NGINX.
```

2021-02-09 16:28 UTC, cromefire commented on docker/README.md
> +
```suggestion
```

2021-02-09 16:28 UTC, cromefire commented on docker/LICENSE
> +SOFTWARE.
I think that file can go, as there already is a license in ther repo, maybe we want to add @xthursdayx to the license in the root though.

2021-02-09 16:28 UTC, cromefire commented on docker/.gitignore
> +database/adonis.sqlite
```suggestion
*.sqlite
```

2021-02-09 16:28 UTC, cromefire commented on README.md
> +For more information on configuring the Docker image, please read [./docker/README.md](https://github.com/getferdi/server/tree/master/docker/README.md).
```suggestion
For more information on configuring the Docker image, please read [the ferdi docker documentation](./docker/README.md).
```

2021-02-09 16:28 UTC, cromefire commented on README.md
> +    Alternatively, you can also use docker-compose v2 schemas. An example can be found in [./docker/docker-compose.yml](https://github.com/getferdi/server/tree/master/docker/docker-compose.yml) file.
```suggestion
    Alternatively, you can also use docker-compose v2 schema. An example can be found [in the docker folder](./docker/docker-compose.yml) file.
```

2021-02-09 16:28 UTC, cromefire commented on .dockerignore
> +README-secret.md
```suggestion
# ignore all markdown files
*.md
```

2021-02-09 16:28 UTC, cromefire commented on .dockerignore
> +# ignore other directories
```suggestion
# Ignore database files
*.sqlite

# ignore other directories
```

2021-02-09 20:14 UTC, k0staa commented on docker/.gitignore
> +database/adonis.sqlite
I will change that and move to root .gitignore

2021-02-09 20:31 UTC, k0staa commented
Please check it out @cromefire -> [https://github.com/getferdi/server/pull/48/commits/0a3ce5a9e37dd917cfabdf97fdc18a41d88c65eb](https://github.com/getferdi/server/pull/48/commits/0a3ce5a9e37dd917cfabdf97fdc18a41d88c65eb).
I think I have addressed all of the topics :wink:

2021-02-09 20:31 UTC, cromefire commented on docker/README.md
> +**Warning ,using `config.txt` will be deprecated in the future releases.**
```suggestion
**Warning, using `config.txt` will be deprecated in the future releases.** 
```

2021-02-09 20:34 UTC, cromefire commented on docker/README.md
> +
I think we can remove this, as it's now just some documentation inside of the repo and we probably don't need the logo file either

2021-02-09 20:36 UTC, cromefire commented on docker/README.md
> +The docker can be run as is, with the default sqlite database, or you can modifying your ENV variables to use an external database (e.g. MYSql, MariaDB, Postgres, etc). After setting up the docker co
This makes some strong assumptions, I edited it a bit to reflect the nature of those recommendations/examples

2021-02-09 20:37 UTC, cromefire commented on docker/README.md
> +| MySQL | mysql |
Just some clutter that's not particularly bad, but you know 🤷

2021-02-09 20:39 UTC, cromefire commented
There's a few unanswered/unchanged ones left

2021-02-09 20:43 UTC, k0staa commented on .dockerignore
> +# ignore other directories
Fixed in [https://github.com/getferdi/server/commit/0a3ce5a9e37dd917cfabdf97fdc18a41d88c65eb](https://github.com/getferdi/server/commit/0a3ce5a9e37dd917cfabdf97fdc18a41d88c65eb)

2021-02-09 20:44 UTC, k0staa commented on .dockerignore
> +README-secret.md
Fixed in [https://github.com/getferdi/server/commit/0a3ce5a9e37dd917cfabdf97fdc18a41d88c65eb](https://github.com/getferdi/server/commit/0a3ce5a9e37dd917cfabdf97fdc18a41d88c65eb)

2021-02-09 20:44 UTC, k0staa commented on README.md
> +    Alternatively, you can also use docker-compose v2 schemas. An example can be found in [./docker/docker-compose.yml](https://github.com/getferdi/server/tree/master/docker/docker-compose.yml) file.
Fixed in [https://github.com/getferdi/server/commit/0a3ce5a9e37dd917cfabdf97fdc18a41d88c65eb](https://github.com/getferdi/server/commit/0a3ce5a9e37dd917cfabdf97fdc18a41d88c65eb)

2021-02-09 20:45 UTC, k0staa commented on README.md
> +For more information on configuring the Docker image, please read [./docker/README.md](https://github.com/getferdi/server/tree/master/docker/README.md).
Fixed in [https://github.com/getferdi/server/commit/0a3ce5a9e37dd917cfabdf97fdc18a41d88c65eb](https://github.com/getferdi/server/commit/0a3ce5a9e37dd917cfabdf97fdc18a41d88c65eb)

2021-02-09 20:45 UTC, k0staa commented on docker/.gitignore
> +database/adonis.sqlite
Fixed in [https://github.com/getferdi/server/commit/0a3ce5a9e37dd917cfabdf97fdc18a41d88c65eb](https://github.com/getferdi/server/commit/0a3ce5a9e37dd917cfabdf97fdc18a41d88c65eb)

2021-02-09 20:45 UTC, cromefire commented
I think you missed those where you have to click the load more button

2021-02-09 20:46 UTC, k0staa commented on docker/README.md
> +- `Recipe files`: Recipe files that you created using the [Franz recipe creation guide](https://github.com/meetfranz/plugins/blob/master/docs/integration.md). Please do *not* package your files befor
I leave that as it is. I don't have enough info about it to make the change.

2021-02-09 20:46 UTC, k0staa commented on docker/README.md
> +* **25.09.19:** - Initial Release.
Fixed in [https://github.com/getferdi/server/commit/0a3ce5a9e37dd917cfabdf97fdc18a41d88c65eb](https://github.com/getferdi/server/commit/0a3ce5a9e37dd917cfabdf97fdc18a41d88c65eb)

2021-02-09 20:46 UTC, k0staa commented on docker/entrypoint.sh
> +fi
Fixed in [https://github.com/getferdi/server/commit/0a3ce5a9e37dd917cfabdf97fdc18a41d88c65eb](https://github.com/getferdi/server/commit/0a3ce5a9e37dd917cfabdf97fdc18a41d88c65eb)

2021-02-09 20:50 UTC, k0staa commented on docker/LICENSE
> +SOFTWARE.
I'm not sure about legal aspects of the license, but maybe I will just add Ferdi to the main one?

2021-02-09 20:53 UTC, k0staa commented on docker/README.md
> +| Ethereal | A disposable account is created automatically if you choose this option. |
If so then imho we should add this information.

2021-02-09 21:00 UTC, k0staa commented on docker/README.md
> +| Ethereal | A disposable account is created automatically if you choose this option. |
Fixed in [https://github.com/getferdi/server/pull/48/commits/88c94fbb301f7778f288d08e6daa81bef96a7e7f](https://github.com/getferdi/server/pull/48/commits/88c94fbb301f7778f288d08e6daa81bef96a7e7f)

2021-02-09 21:07 UTC, k0staa commented on docker/README.md
> +The docker can be run as is, with the default sqlite database, or you can modifying your ENV variables to use an external database (e.g. MYSql, MariaDB, Postgres, etc). After setting up the docker co
true, I will fix that.

2021-02-09 21:24 UTC, k0staa commented on docker/LICENSE
> +SOFTWARE.
Ok, I guess we need to sort this out. @xthursdayx can I delete this license file from this directory (`docker/LICENSE`) ? @vantezzen can I remove your username and add **Ferdi** to the master license as copyright holder or add @xthursdayx to it ?

2021-02-09 23:36 UTC, cromefire commented on docker/LICENSE
> +SOFTWARE.
So **legally** it's MIT, so you can basically do what every you want:

> to use, copy, modify, merge, publish, distribute, **sublicense**, and/or sell

But checking in with the people involved is probably a good idea.

2021-02-09 23:38 UTC, cromefire approved these changes

2021-02-10 10:11 UTC, k0staa commented on docker/LICENSE
> +SOFTWARE.
Yes, I will wait for response from @vantezzen  and @xthursdayx

2021-02-10 19:48 UTC, vantezzen commented on docker/LICENSE
> +SOFTWARE.
Yes, feel free to replace my username with Ferdi in the licenses

2021-02-14 09:19 UTC, k0staa commented
I think it is ready to merge.
**I don't have access to Docker Hub so there are still a few things to check/do:**
 - set up a new repository in Docker Hub Automated builds 
 - set up appropriate README.md. The default logic of Docker Hub Automated Builds is that it gets the `README.md` from the directory where `Dockerfile` resides (`Dockerfile` directory can be configured). If this can't be changed somehow in configuration and we want to use this `README.md` from `docker` directory, we will have to move the `Dockerfile` to the` docker` directory or edit the Docker Hub description manually. Docs -> [https://docs.docker.com/docker-hub/builds/](https://docs.docker.com/docker-hub/builds/)

fyi: @cromefire @xthursdayx @kytwb

2021-02-14 12:17 UTC, cromefire commented
I have seem other repos with different descriptions, so I guess that's possible (can't check)

2021-02-14 19:36 UTC, xthursdayx commented on docker/LICENSE
> +SOFTWARE.
Yep, happy for you to remove it. These are just remanents from my original image.

2021-02-14 19:51 UTC, xthursdayx commented
Just 

> I think it is ready to merge.
> **I don't have access to Docker Hub so there are still a few things to check/do:**
> 
> * set up a new repository in Docker Hub Automated builds
> * set up appropriate README.md. The default logic of Docker Hub Automated Builds is that it gets the `README.md` from the directory where `Dockerfile` resides (`Dockerfile` directory can be configured). If this can't be changed somehow in configuration and we want to use this `README.md` from `docker` directory, we will have to move the `Dockerfile` to the` docker` directory or edit the Docker Hub description manually. Docs -> https://docs.docker.com/docker-hub/builds/
> 
> fyi: @cromefire @xthursdayx @kytwb

I just looked into created a new Docker Hub repo and changing the `Dockerfile` location for Dockerhub automated builds isn't a problem at all, though I'm not sure how to go about having the `README.md` automatically pulled in. It might have to be edited manually if we don't want to move the `Dockerfile` then I think the only option is to edit the Docker Hub description manually. 

However the issue now is that Docker Hub still isn't recognizing the Server or Server-docker Github repos. I'd like to try to reattach the `getferdi` organization to the `getferdi` Github account, but the only way to do that is via the service account `ferdibot` we created on Docker Hub. I don't have the `ferdibot` login info, so do one of you either want to log into Docker Hub as `ferdibot` and try reattaching the `getferdi` Github to the `getferdi` Docker Hub organization @kytwb @vantezzen , or one of you want to send me the login info and I'm happy to do it.

2021-02-27 17:07 UTC, k0staa commented
Maybe we could somehow unblock this pull request. It would be nice to merge it, we put a lot of work into it :smiley: 
@kytwb @vantezzen

2021-07-05 14:16 UTC, vraravam approved these changes

2021-07-06 19:31 UTC, xthursdayx commented
> I just looked into created a new Docker Hub repo and changing the `Dockerfile` location for Dockerhub automated builds isn't a problem at all, though I'm not sure how to go about having the `README.md` automatically pulled in. If we don't want to move the `Dockerfile` then I think the only option is to edit the Docker Hub description manually.
> 
> However, the issue now is that Docker Hub still isn't recognizing the `server` or `server-docker` Github repos. I'd like to try to reattach the `getferdi` Docker Hub organization to the `getferdi` Github account, but the only way to do that is via the service account `ferdibot` we created on Docker Hub. I don't have the `ferdibot` login info, so either one of your can log into Docker Hub as `ferdibot` and try reattaching the `getferdi` Github to the `getferdi` Docker Hub organization @kytwb or @vantezzen , or who has it can send me the login info and I'll be happy to do it.

So, I'm happy to merge this PR to pull the docker-server into this repo and bring the main image up to date with all of the work you all have put in, however, I still don't have access to the Docker Hub ferdibot service account, so can't update the Docker Hub auto-build process which will be an important part of redeploying the docker image if we plan to continue using Docker Hub auto-builds.

The other option is develop a Github workflow to build and publish the docker image. I've been experimenting with this with other images I manage and it seems to be a good way to get around some of the constraints associated with Docker Hub's auto-build process - particularly now that Docker Hub is discontinuing auto-builds on non-enterprise accounts. Using a Github workflow (and a couple of new Dockerfiles) can also allow us to develop the ferdi-server docker image as a multi-arch image with a manifest, so that end users will automatically pull the correct image for their system (e.g. amd64, arm64, armhf).  I'm in the process of implementing this on another image, so I can work on that here if we choose to go that route.

2021-07-07 02:11 UTC, vraravam commented
> The other option is develop a Github workflow to build and publish the docker image. I've been experimenting with this with other images I manage and it seems to be a good way to get around some of the constraints associated with Docker Hub's auto-build process - particularly now that Docker Hub is discontinuing auto-builds on non-enterprise accounts. Using a Github workflow (and a couple of new Dockerfiles) can also allow us to develop the ferdi-server docker image as a multi-arch image with a manifest, so that end users will automatically pull the correct image for their system (e.g. amd64, arm64, armhf). I'm in the process of implementing this on another image, so I can work on that here if we choose to go that route.

I totally agree with this approach. I like to have a single CI tool for different target architectures. Since we have moved all of our CI tooling to GH Actions (from Travis-CI and Appveyor), I concur that this seems to be the best course of action.

@xthursdayx - this PR says that it cannot be rebased due to conflicts - please fix them, rebase to the latest `HEAD` and we can quickly review and approve this PR.

2021-07-08 08:16 UTC, xthursdayx commented
> I totally agree with this approach. I like to have a single CI tool for different target architectures. Since we have moved all of our CI tooling to GH Actions (from Travis-CI and Appveyor), I concur that this seems to be the best course of action.
> 
> 
> 
> @xthursdayx - this PR says that it cannot be rebased due to conflicts - please fix them, rebase to the latest `HEAD` and we can quickly review and approve this PR.

Glad to hear that we're on the same page re: GitHub actions to build and publish. I'm on my phone right now and can't see the rebasing issues, but this is not my PR anyway, the work on this PR and the PR

2021-07-08 09:02 UTC, cromefire commented
> which involved replacing s6 with an entrypoint script if I remember correctly

Yeah I think I i removed all of the Linux Server base image nonsense in favor of a much slimmer image (s6 isn't really needed nowadays, because docker itself provides an init process and we don't need more than one process)

2021-07-08 09:06 UTC, vraravam requested changes

2021-07-08 09:06 UTC, vraravam commented on .gitignore
> +*.sqlite
I guess this is related to the previous comment.

2021-07-08 09:06 UTC, vraravam commented on Dockerfile
> +RUN ["apk", "add", "--no-cache", "python", "make", "gcc", "g++", "libc-dev", "sqlite-dev"]
Can we please change this to:
```
RUN apk add --no-cache python make gcc g++ libc-dev sqlite-dev
```
(its easier for maintainers to understand - imo)

2021-07-08 09:06 UTC, vraravam commented on Dockerfile
> +RUN ["npm", "ci", "--production", "--build-from-source", "--sqlite=/usr/local"]
same here:
```
RUN npm ci --production --build-from-source --sqlite=/usr/local
```

2021-07-08 09:06 UTC, vraravam commented on Dockerfile
> +RUN ["apk", "add", "--no-cache", "sqlite-libs", "curl"]
same here:
```
RUN apk add --no-cache sqlite-libs curl
```

2021-07-08 09:06 UTC, vraravam commented on Dockerfile
> +ENV HOST=0.0.0.0 PORT=3333
maybe a nitpick: I prefer each environment value to be in its own line. Or is there a benefit to doing it all in one line?

2021-07-08 09:06 UTC, vraravam commented on Dockerfile
> +
Please add a `TODO` (or implement it) where the user running the process is not `root`.

2021-07-08 09:07 UTC, cromefire commented on .dockerignore
> +.git
.gitattributes for example would need to be included

2021-07-08 09:11 UTC, cromefire commented on Dockerfile
> +RUN ["apk", "add", "--no-cache", "python", "make", "gcc", "g++", "libc-dev", "sqlite-dev"]
This doesn't require the use of the shell, so it has different semantics, I'd prefer to not use the shell if it's not necessary. Less errors, less resource usage, etc.

2021-07-08 09:12 UTC, cromefire commented on Dockerfile
> +ENV HOST=0.0.0.0 PORT=3333
Well it's one step less in the docker build and every step hat an inherent time it takes while building

2021-07-08 22:43 UTC, xthursdayx commented on .env.example
> -DATA_DIR=data
In the resolved conversations in  commit https://github.com/getferdi/server/pull/48/commits/bbd2132feede2d8c5e214c4d8a436f5505b9a766 @cromefire and @k0staa argue for deprecating the method of saving Ferdi-server's config values in a `config.txt` file in `/config`, and for having better documentation regarding what environmental variables user should pass to the container (by whatever means, whether docker-compose or other). I think the removal of `data` here is due to to the fact that they are expecting the user to pass the `DATA_DIR` variable.  The PR updates the `README.MD` to note that the use of the `config.txt` is deprecated and both the readme and example `docker-compose.yml` file suggest setting `DATA_DIR=data`. However, I think it is probably unnecessary to change `DATA_DIR=data` to `DATA_DIR=` in the `.env.example`. 

This will depend on how the .env.example file is used. The current version of the `entrypoint.sh` script in this PR still checks for a config.txt with the lines:
```
if [ -f /config/config.txt ]; then
    cp /config/config.txt /app/.env
else
    cp /app/.env.example /app/.env
fi
``` 
My opinion is that if we're going to introduce as significant of a change as merging the docker repo into the main server repo then we may as well get rid of the config.txt all together. 

If I recall correctly, I ended up using the `config.txt` method because I was running into problems with having the container overwrite any existing `.env` file in the `/config` directory with the default `.env.example` variables when the container was restarted. This issue and resulting approach was probably the result of my own inexperience and lack of knowledge more than anything else, but it was what seemed to work best to me at the time. 

If the redesigned container maintains user supplied variables in `/config/.env`, then I'd be happy to see that section of code I quoted above removed along with any reference to config.txt. 

What are your thoughts @cromefire and @k0staa ?

2021-07-08 22:44 UTC, xthursdayx commented on .gitignore
> +*.sqlite
I don't see the problem. Wouldn't this ignore any .sqlite file, or would it only ignore an .sqlite file at root?

2021-07-08 23:12 UTC, xthursdayx commented
It seems that one of the major reasons for this PR and merging the `server-docker` into this repo is to simplify the process pf running of the server in a docker container (and maintaining the server and docker image) and to work towards building the server in a production rather than development node environment. Because of that, I wonder if it makes sense to work towards merging this PR before PR https://github.com/getferdi/server/pull/46 is completed and merged? 

Am I correct in assuming, that once PR https://github.com/getferdi/server/pull/46 is resolved, it will address the concerns raised in issues https://github.com/getferdi/server-docker/issues/8 and https://github.com/getferdi/server/issues/45 , which will mean that we can change line 3 in `.env.example` from `NODE_ENV=development` to `NODE_ENV=production`, along with the associated lines in the `README.md` and `docker-compose.yml`?

To my mind, creating a pre-built docker image (as suggested here: https://github.com/getferdi/server-docker/pull/9 ) and merging the docker code into the main server repo both to some degree depend on upgrading the Adonis components used. What do you all think?

2021-07-08 23:18 UTC, cromefire commented
Prebuilt Image does depend on the Adonis upgrade, as the older Adonis version doesn't really support building afaik

2021-07-08 23:24 UTC, cromefire commented
That doesn't prevent the image from being improved though, as that can still be done in the current state

2021-07-09 02:23 UTC, xthursdayx commented on Dockerfile
> +RUN ["apk", "add", "--no-cache", "python", "make", "gcc", "g++", "libc-dev", "sqlite-dev"]
In relation to this I don't have an opinion either way. I am used to creating Dockerfiles that rely on shell, so am more familiar with the way `RUN` line variant @vraravam suggests, but I'm open to the alternative if you believe that it results in meaningful savings in resource in time, then I'm open to it. I'm not clear why it change any errors as I haven't seen any errors with lines like `RUN apk add --no-cache python make gcc g++ libc-dev sqlite-dev` in Dockerfiles anyway, but, again, am open to learning otherwis.

2021-07-09 02:26 UTC, xthursdayx commented on Dockerfile
> +RUN ["npm", "ci", "--production", "--build-from-source", "--sqlite=/usr/local"]
Same as above.

2021-07-09 02:54 UTC, xthursdayx commented on Dockerfile
> +RUN ["npm", "ci", "--production", "--build-from-source", "--sqlite=/usr/local"]
Also, will this work with `--production` flag, since the image will currently only work with adonis run in `development` mode? Or are they unrelated. If so, please excuse my ignorance.

2021-07-09 03:05 UTC, xthursdayx commented on Dockerfile
> +ENV HOST=0.0.0.0 PORT=3333
I agree with @cromefire 's goal of aiming for fewer steps. I tend to use one `ENV` command with values separated on multiple lines using `\`, just for clarity when reading. Same with my `RUN` commands. For example:
```
ENV HOST=0.0.0.0 \
         PORT=3333
```
Is there any problem doing it this way, since during build it will be read as `ENV HOST=0.0.0.0. PORT=3333` anyway?

2021-07-09 03:06 UTC, xthursdayx commented on Dockerfile
> +RUN ["apk", "add", "--no-cache", "sqlite-libs", "curl"]
Same as the last two on my end.

2021-07-09 04:10 UTC, xthursdayx commented on Dockerfile
> +
I already responded to this, but I guess it didn't post. Running the process as `root` was my primary reason for originally choosing to use the LSIO alpine baseimage with s6. If there is a good way to drop privileges and change user when starting the server using Docker's built-in init system, then I'd support that. 

I know it's possible to `USER <user>[:<group>]` or `USER <UID>[:<GID>]` in the `Dockerfile` to set the user executing any `RUN`, `CMD` and `ENTRYPOINT` instructions that follow it, however as the `entrypoint.sh` scrip is currently written, I believe that at least some of the commands need to be run as `root` (though I could be wrong, which would make this easier).

In order to run as ferdi-server as `root` using the new image design, I assume that the either the `Dockerfile` or `entrypoint.sh` script would need to create a new user (e.g. `ferdi`), define their `PUID` and `PGID`, and give them ownership ownership over the directories `/config` and `/app`. Of course, the use of `PUID` and `PGID` could be an opportunity to add additional user-submitted environmental variables in order to match their mounted file system directories.

My broader question is whether it would then be possible to either run all of `entrypoint.sh` as the user ferdi using the `USER` command in the Dockerfile and still have `entrypoint.sh` work correctly, or whether it would be better (or possible) to run the line `exec node server.js` using [su-exec](https://github.com/ncopa/su-exec), for example `su-exec ferdi node server.js`? Or would the user `ferdi` not have the privileges to run `node` commands?

What is the best strategy in general? My gut says creating a `ferdi` user in the `Dockerfile` defined with the `uid:gid` `1000`, home as `/confg` and shell as `/bin/false`, for example:
```
 useradd -u 1000 -U -d /config -s /bin/false ferdi && \
 usermod -G users ferdi && \

```
Then in the `entrypoint.sh` script changing `PUID` and `PGID` based on the user `PUID` & `PGID` input, for example:
```
PUID=${PUID:-1000}
PGID=${PGID:-1000}

groupmod -o -g "$PGID" ferdi
usermod -o -u "$PUID" ferdi
```
Again, I'm not sure then if the user `ferdi` would be able execute the node commands or not, but it's the first approach for dropping privileges that came to mind.

2021-07-09 04:47 UTC, vraravam commented on Dockerfile
> +
Nice writeup @xthursdayx - At the bare minimum, I would request that you put a `TODO` and move on. We can tackle the questions that you asked in a later PR. The reason I am insisting at least the bare minimum is that I would like such a dialog to at least happen as we touch code. The `TODO` will serve as a reminder that there's some kind of tech debt. And If you put this PR / conversation link in there, then the next dev can follow up and carry on. Hope that makes sense.

2021-07-09 04:49 UTC, vraravam commented on Dockerfile
> +ENV HOST=0.0.0.0 PORT=3333
I'm fine with this approach since there's at least one other person (@xthursdayx ) who has chimed in. Something that I learnt by this: that multiple env vars can be done with the `=` and space separations.

2021-07-09 04:53 UTC, vraravam commented on Dockerfile
> +RUN ["apk", "add", "--no-cache", "python", "make", "gcc", "g++", "libc-dev", "sqlite-dev"]
I still prefer the single line - for ease of understanding. But, am willing to leave it be - because I would like us to finish this PR and get this merged soon.

2021-07-09 04:57 UTC, vraravam commented on .env.example
> -DATA_DIR=data
> My opinion is that if we're going to introduce as significant of a change as merging the docker repo into the main server repo then we may as well get rid of the config.txt all together.

Huge +1

2021-07-09 04:58 UTC, vraravam commented on .gitignore
> +*.sqlite
Its just that this is tied to whether we use the `data` directory or not.

2021-07-09 05:01 UTC, vraravam commented
> That doesn't prevent the image from being improved though, as that can still be done in the current state. (And as stated, the upgrade might take a while)

Right. So, can we table the adonis upgrade out of this PR - and get this into an acceptable/mergeable state?

2021-07-09 05:35 UTC, cromefire commented on Dockerfile
> +RUN ["npm", "ci", "--production", "--build-from-source", "--sqlite=/usr/local"]
This is a different `--production`

2021-07-09 05:44 UTC, cromefire commented on .env.example
> -DATA_DIR=data
The redesign image wouldn't use any `.env` anymore, you can use a `.env` with compose though

2021-07-09 05:50 UTC, cromefire commented on Dockerfile
> +
I'd put a Todo here for now and later you can just create the user in the dockerfile and set it too. For security though I'd recommend running something like gVisor and/or dockerd as non-root.

2021-07-09 06:04 UTC, xthursdayx commented on .env.example
> -DATA_DIR=data
So, if the redesigned image won't use any `.env`, I assume we can completely remove both the this code from the `entrypoint.sh`:
```
if [ -f /config/config.txt ]; then
    cp /config/config.txt /app/.env
else
    cp /app/.env.example /app/.env
fi
```
and the `.env.example`, unless you want to keep that as an example for people who would like to use an `.env` file with compose.

2021-07-09 06:10 UTC, cromefire commented on .env.example
> -DATA_DIR=data
I'd leave the `.env.example` as documentation I guess, but it wouldn't be used by the image. But especially as it should be possible to run the server without docker, if that's what someone seeks for, keeping it and commenting it would probably be a good idea.

2021-07-09 06:13 UTC, xthursdayx commented on .gitignore
> +*.sqlite
Right, I understand, but it sounds like the redesigned image will solely use environmental variables submitted by the user directly, via a docker-compose, in an .env file with compose, or by another means (like unRAID's Dockerman). So, it sounds like it will be up to the user where they map `DATA_DIR` to, though the `README.md` and example `docker-compose.yml` both suggest `DATA_DIR=data`. So I guess my question is this - if the user follows the instructions in the `READMEmd` and/or uses the provided example `docker run` command or `docker-compose.yml`, will having `*.sqlite` in the `.gitignore` suffice, or will it need to specify the data directory that the `sqlite` db is in (assuming users will use `data`)?

2021-07-09 06:17 UTC, cromefire commented on .gitignore
> +*.sqlite
Oh no, that one is for testing and debugging if you are developing and then you build an image you have to exclude it, otherwise you'd get a dirty build.
Regarding the data dir, there should be a default in place in the code (if not this should probably be added, I think it's at least there after the upgrade)

2021-07-09 06:35 UTC, xthursdayx commented on .gitignore
> +*.sqlite
Is that default data dir the one that was removed from the `.env.example` above, or does it exist somewhere else in the server code? Because I don't see a default `DATA_DIR` anywhere else in the docker code (which h'm more familiar with than the base server code).

2021-07-09 07:03 UTC, xthursdayx commented on .env.example
> -DATA_DIR=data
See my comments on the .gitignore below. I'm happy to leave the `config.txt` code in the entrypoint.sh but comment it out and include the .env.example as documentation for those who want to use an .env file. However, if I understand your comment on the .gitignore correctly, it seems that the default DATA_DIR needs to be included in the docker code somewhere, unless I missed it or misunderstood you.

2021-07-09 07:13 UTC, xthursdayx commented on Dockerfile
> +
> I'd also just put a Todo here for now and later you can just create the user in the dockerfile and set it too. For security though I'd recommend running something like gVisor and/or dockerd as non-root. As for the permissions I'd have to have a look, this was a hot pile of garbage last time I checked... (Because I think docker just mapped that id to some outside did and called it a day or something along those lines)

I appreciate the security offered by gVisor/runsc and running dockerd as non-root, but I'd prefer to have the container run the server as non-root internally, since these other solutions rely on end user implementation, which is unreliable at best.

2021-07-09 07:18 UTC, xthursdayx commented
> Right. So, can we table the adonis upgrade out of this PR - and get this into an acceptable/mergeable state?

Yes, I'm happy to table the privileges issue with a TODO and merge this PR prior to the adonis upgrade. I think the last things to be sorted out are the inclusion of a default `DATA_DIR` if this doesn't exist.  See the comments on `.env.example` and `.gitignore`.

2021-07-09 07:33 UTC, cromefire commented on .gitignore
> +*.sqlite
There should be a `getEnv` somewhere with a default value.
As that's not the case it seems like (ot it has a wrong value at least) this should probably be fixed.

2021-07-09 07:35 UTC, cromefire commented on .gitignore
> +*.sqlite
I mean these are breaking changes anyway, so so let's try and squeeze most of the breaking changes in here (we should probably include a migration path though).

2021-07-09 08:45 UTC, xthursdayx commented on .gitignore
> +*.sqlite
> I mean these are breaking changes anyway, so so let's try and squeeze most of the breaking changes in here (we should probably include a migration path though).

These are pretty much my thoughts as well (which one reason I was hoping we could squeeze in Adonis upgrade as well…). 

I’m terms of a `getENV`, the lines I see are 31-37 in database.js:
```
  sqlite: {
    client: 'sqlite3',
    connection: {
      filename: Helpers.appRoot(`${Env.get('DATA_DIR', 'database')}/${Env.get('DB_DATABASE', 'development')}.sqlite`),
    },
    useNullAsDefault: true,
    debug: Env.get('DB_DEBUG', false),
```
I don’t know if that section is correct or not, given tbe updates to the image (though I assume they’re still working as planned for the server itself), but I remember something about @k0staa removing `Helpers.appRoot`part in an earlier commit (either here or in the PR in the server-docker repo, you and @k0staa worked on), and then reverting the changes to avoid breaking changes.

As we agree, since we’re making breaking changes, we may as well lump them all together, so long as those changes don’t break the functionality of the server for people running it un-dockerized (for development or otherwise).

2021-07-09 09:02 UTC, cromefire commented on .gitignore
> +*.sqlite
The new default for `DATA_DIR` should probably be `data` and for `DATABASE` it should probably be `database` or something similar (development doesn't sound like a good default) and then we should probably advise users to set them to `database` and `development` if they want backwards compatibility

2021-07-09 18:51 UTC, xthursdayx commented on .gitignore
> +*.sqlite
Okay, just to be completely clear, does that mean then that this line in `database.js`
```
filename: Helpers.appRoot(`${Env.get('DATA_DIR', 'database')}/${Env.get('DB_DATABASE', 'development')}.sqlite`),
```
should become:
```
filename: Helpers.appRoot(`${Env.get('DATA_DIR', 'data')}/${Env.get('DB_DATABASE', 'database')}.sqlite`),
```
or should it become:
```
filename: `${Env.get('DATA_DIR', 'data')}/${Env.get('DB_DATABASE', 'database')}.sqlite`,
```
which is basically the line added by @k0staa in commit https://github.com/getferdi/server/pull/48/commits/794108b4d555d82e59d476d823d5cb87791a67fc (with the variables `data` and `database` used respectively in place of `database` and `development`, which were the values in that commit and those in the existing `database.js`), which you and he decided to change back in order to avoid breaking changes?

Either way, I assume that when you mention documentation and migration path that would meaning rewriting line 13 in the `.env.example` as `DATA_DIR=data`, and updating line 20 to `DB_DATABASE=database`, and then echoing these variables in the `README.md` and `docker-complose.yml`? Or is there anything else we need to add?

Once this is clear I can make the changes later today and the PR should be ready to merge, I hope.

2021-07-09 19:05 UTC, cromefire commented on .gitignore
> +*.sqlite
I think the latter would be correct. By migration path I think we should document that existing users should set those variables to `database` and `development` for compatibility reasons.

2021-07-09 22:17 UTC, xthursdayx reviewed
Please check the most recent commits I added to this PR. If they all check out I believe that the PR is ready to be merged.

2021-07-09 22:17 UTC, xthursdayx commented on docker/README.md
> +**Existing users please note:** The latest updates to Ferdi-server and the Ferdi-server Docker image introduce changes to the default sqlite database name and location, please see the comments in the
Please review the warning for existing users here and on lines 78-79. I have also corrected the spelling and grammar throughout the README, so please check that everything is correct.

2021-07-09 22:17 UTC, xthursdayx commented on docker/README.md
> +| `-p <port>:3333` | Will map the container's port 3333 to a port on the host, default is 3333 |
Please ensure that this is correct - it was still listed as mapping host port 3333 to container port 80, which I believe is no longer correct.

2021-07-10 03:31 UTC, vraravam commented on config/database.js
> +      filename: `${Env.get('DATA_DIR', 'data')}/${Env.get('DB_DATABASE', 'database')}.sqlite`,
Also, isn't it better to use the `path.join` so that this works consistently between windows and unix style path-separators?

2021-07-10 03:33 UTC, vraravam commented
Also - can I please request you to rebase from the `master` branch before the final review? (so that squashing and rebasing seamless - and the reviewer can understand your complete changes in an atomic logical unit.)

2021-07-10 05:26 UTC, xthursdayx commented on config/database.js
> +      filename: `${Env.get('DATA_DIR', 'data')}/${Env.get('DB_DATABASE', 'database')}.sqlite`,
I don't know anything about `path.join`, so someone else will have to answer that (and the question about the default db names).

2021-07-10 05:32 UTC, xthursdayx commented on .gitignore
> +*.sqlite
I think that this should be good to go now, but please have a look at my more recent commits. Cheers!

2021-07-10 09:30 UTC, xthursdayx commented
> Also - can I please request you to rebase from the `master` branch before the final review? (so that squashing and rebasing seamless - and the reviewer can understand your complete changes in an atomic logical unit.) I believe that I've updated everything from the `master` in this PR via @k0staa 's branch. If everyone if happy with my chances I think we should be ready to merge (ideally after deciding if we want to strive for consistency and have ALL databases (internal and external use something specific like `ferdi` rather than `adonis`, unless of course that's necessary for Adonis for some reason.

2021-07-10 10:14 UTC, vraravam commented
@xthursdayx - the PR (in the Github web portal) still shows "Resolve conflicts" - so, I dont think its up-to-date yet. (Or maybe its @k0staa 's fork/branch?)

2021-07-10 11:33 UTC, xthursdayx commented
> @xthursdayx - the PR (in the Github web portal) still shows "Resolve conflicts" - so, I dont think its up-to-date yet. (Or maybe its @k0staa 's fork/branch?)

Feel free to have a look and see if you can identity/fix the code the is holding back the rebase. I didn't my best, and identitied a number of issues, but it seems there are still more left.

2021-07-10 18:24 UTC, xthursdayx commented on config/database.js
> +      filename: `${Env.get('DATA_DIR', 'data')}/${Env.get('DB_DATABASE', 'database')}.sqlite`,
Would this be as simple as changing line 34 to be: `filename: path.join`${Env.get('DATA_DIR', 'data')}/${Env.get('DB_DATABASE', 'database')}.sqlite`,` ?

I don't really know NodeJS, so could be totally wrong.

2021-07-10 18:28 UTC, xthursdayx commented
I'm happy to merge this PR now, my only lingering questions (which I asked in my review above) relate to the `database.js` file (and accompanying documentation), and whether it is necessary to call the default non-SQLite database `adonis` or whether we can switch it to something that relates more directly to the project, like `ferdi`. 

I also posted a suggested code change based on @vraravam 's question  about using `path.join` to allow the server to work consistently between windows and unix style path-separators, but someone else should check it because my chage could be completely incorrect.

2021-07-11 00:02 UTC, vraravam commented on config/database.js
> +      filename: `${Env.get('DATA_DIR', 'data')}/${Env.get('DB_DATABASE', 'database')}.sqlite`,
yes, break all strings that have `/` in them into elements of an array - and pass that into `path.join`

2021-07-11 00:03 UTC, vraravam commented on config/database.js
> +      filename: `${Env.get('DATA_DIR', 'data')}/${Env.get('DB_DATABASE', 'database')}.sqlite`,
and then you might not need string interpolation (if each element is a self-container expression being evaluated)

2021-07-11 06:12 UTC, xthursdayx commented on config/database.js
> +      filename: `${Env.get('DATA_DIR', 'data')}/${Env.get('DB_DATABASE', 'database')}.sqlite`,
would that still allow for ENV input with default fallback options like the current code?

2021-07-11 06:25 UTC, vraravam commented on config/database.js
> +      filename: `${Env.get('DATA_DIR', 'data')}/${Env.get('DB_DATABASE', 'database')}.sqlite`,
Yes - interpolation is using the tick "`" mark, whereas the `Env.get` would still allow for the ENV-based overrides.

To remove confusion, this is what I was suggesting for that line of code to change to:
```
filename: path.join(Env.get('DATA_DIR', 'data'), `${Env.get('DB_DATABASE', 'development')}.sqlite`),
```
assuming that you have imported `path` up at the top.

2021-07-11 06:27 UTC, vraravam commented on .env.example
> +DB_DATABASE=database
I would prefer to have `ferdi` along with the env (`development`?) appear in the db name.

2021-07-11 06:32 UTC, xthursdayx commented
@cromefire I recognize that it's the weekend now and this isn't really a major priority, but if you get a chance would you mind checking my recent commits and the questions I posted to the review? Your feedback is particularly helpful since you did so much of the redesign. Same goes for you @k0staa 

Either way, thanks for all you hard work! I'm not a pro, just a hobbyist, so I continue to learn as I go along and I've learned a lot from these exchanges!

2021-07-11 09:31 UTC, cromefire commented
Yeah I meant to, weekend is normally my primary time for OSS stuff, but didn't have time yesterday, expect something later today.

2021-07-11 12:37 UTC, cromefire commented on .env.example
> +DB_DATABASE=database
Well it should probably be something like `ferdi` by default, now that I think about it. `development` doesn't make any sense at all for a normal user at all (plus it's something more like a production deployment). Using the app name as dbname also makes more sense for user (like me) that use a DBMS, where multiple applications might share a DBMS, so using the app as a dbname likely makes the most sense.

2021-07-11 12:40 UTC, cromefire commented on config/database.js
> +      filename: `${Env.get('DATA_DIR', 'data')}/${Env.get('DB_DATABASE', 'database')}.sqlite`,
> Is there a specific reason (associated with AdonisJS perhaps) for using the default database name `adonis` for the `MySQL` and `Postgrest` connection settings as opposed to something like `ferdi`?

I strongly support making it `ferdi` by default

2021-07-11 12:41 UTC, cromefire commented on .env.example
> +APP_NAME=Ferdi-server
Changing the app name seems fine

2021-07-11 12:44 UTC, cromefire commented on docker/README.md
> +**Existing users please note:** The latest updates to Ferdi-server and the Ferdi-server Docker image introduce changes to the default sqlite database name and location, please see the comments in the
The warning sold be in the main readme, shouldn't it? Because we changed it for everyone, not just docker users.

2021-07-11 12:48 UTC, cromefire commented on docker/README.md
> +| `-p <port>:3333` | Will map the container's port 3333 to a port on the host, default is 3333 |
Maybe we should just state the default port in the docker container here and refer to the docker docs for mapping?

2021-07-11 12:51 UTC, cromefire commented
> > @xthursdayx - the PR (in the Github web portal) still shows "Resolve conflicts" - so, I dont think its up-to-date yet. (Or maybe its @k0staa 's fork/branch?)
> 
> Okay, i figured out what code needed to be resolved and fixed it to rebase to master.

You can usually use some offline git tools to perform these procedures, although simply merging master in to this is usually fine and a rebase has some times been behaving weirdly for me in the past. As a lost option, you can for his branch and open a new PR from that one and close this.

2021-07-11 12:56 UTC, cromefire commented on config/database.js
> +      filename: `${Env.get('DATA_DIR', 'data')}/${Env.get('DB_DATABASE', 'database')}.sqlite`,
> To remove confusion, this is what I was suggesting for that line of code to change to:
> 
> ```
> filename: path.join(Env.get('DATA_DIR', 'data'), `${Env.get('DB_DATABASE', 'development')}.sqlite`),
> ```
> 
> assuming that you have imported `path` up at the top.

Yeah that should work, I forgot, what a PITA nodejs is...

(Also you can write a literal \` using \\`)

2021-07-11 12:57 UTC, cromefire commented on docker/README.md
> +| `-p <port>:3333` | Will map the container's port 3333 to a port on the host, default is 3333 |
(same for the variables, describe the in the main README and like that here along with a link on how to do it in docker)

2021-07-11 12:59 UTC, cromefire commented on docker/docker-compose.yml
> +      - DB_DATABASE=database # existing Ferdi-server users who use the built-in sqlite database should use the database name "development"
Cloud you test it using the current docker image and then upgrading to this PR? If that works it should be fine

2021-07-11 13:16 UTC, vraravam commented
> you can for his branch and open a new PR from that one and close this.

Yes, I know that - but, don't want to hijack his work and plagiarize it. imo, its better for @xthursdayx to fix it.

2021-07-12 05:35 UTC, xthursdayx commented on docker/README.md
> +**Existing users please note:** The latest updates to Ferdi-server and the Ferdi-server Docker image introduce changes to the default sqlite database name and location, please see the comments in the
Maybe both....

2021-07-12 08:46 UTC, cromefire commented on docker/README.md
> +**Existing users please note:** The latest updates to Ferdi-server and the Ferdi-server Docker image introduce changes to the default sqlite database name and location, please see the comments in the
Well, sure

2021-07-12 22:54 UTC, xthursdayx commented on .env.example
> +DB_DATABASE=database
I think it makes sense to switch to the app name as database name, though this is something that will need to be specified in all of the documentation (for both the server and docker).

2021-07-12 22:56 UTC, cromefire commented on .env.example
> +DB_DATABASE=database
I mean this is what we are already changing, we just need to replace the docs with this newer name I guess

2021-07-12 23:24 UTC, vraravam commented
@xthursdayx @cromefire - are you folks ready to merge the PR now? Looks like this branch still has conflicts.
<img width="947" alt="Screenshot 2021-07-13 at 4 54 02 AM" src="https://user-images.githubusercontent.com/69629/125367744-5bd1ae80-e396-11eb-93f5-779d5116c5a6.png">

2021-07-12 23:25 UTC, cromefire commented
Is the migration path tested? That should probably happen before merging too

2021-07-12 23:58 UTC, xthursdayx commented on docker/README.md
> +**Existing users please note:** The latest updates to Ferdi-server and the Ferdi-server Docker image introduce changes to the default sqlite database name and location, please see the comments in the
Added a warning to the main readme and pointed existing users to the docker documentation for  more info.

2021-07-13 00:17 UTC, xthursdayx commented on docker/README.md
> +| `-p <port>:3333` | Will map the container's port 3333 to a port on the host, default is 3333 |
Please check my additions, but I think I've resolved this.

2021-07-13 02:11 UTC, vraravam approved these changes

2021-07-13 02:14 UTC, vraravam approved these changes

2021-07-13 02:27 UTC, vraravam commented on docker/.gitignore
> +# Node modules
My preference (maybe nitpicking) is to have a single `.gitignore` at the root of the project. Easier to understand why some files/folders might have been excluded from git. 
I use nested `.gitignore` only for submodules
If you are ok, please move this file to the project root.

2021-07-13 02:28 UTC, vraravam commented on docker/docker-compose.yml
> +      - NODE_ENV=development
Should this be started in development mode?

2021-07-13 02:29 UTC, vraravam requested changes
Please see my outstanding comments

2021-07-13 02:54 UTC, xthursdayx commented on docker/.gitignore
> +# Node modules
That works for me unless anyone else objects.

2021-07-13 03:18 UTC, xthursdayx commented on docker/docker-compose.yml
> +      - NODE_ENV=development
I believe that @cromefire said no, but can you confirm @cromefire ?

If I remeber correctly this doesn't have anything to do with running adonis with the `--dev` flag when starting ferdi-server, but I'm not sure why this `NODE_ENV` variable needs to be in `development`.

2021-07-13 04:24 UTC, xthursdayx commented on docker/docker-compose.yml
> +      - DB_DATABASE=database # existing Ferdi-server users who use the built-in sqlite database should use the database name "development"
So, I tested the current image using the internal sqlite db with the `data_dir` used and the database name `ferdi` and everything worked fine. I just pull @k0staa 's main branch (the base of this PR) and recieved these errors when building locally: https://pastebin.com/67ZDXQZX

As well as this error: 
```
npm WARN lifecycle ferdi-server@1.1.0~prepare: cannot run in wd ferdi-server@1.1.0 husky install (wd=/server-build)`
```
And these familiar NPM errors:
```
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN deprecated set-value@1.0.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/@adonisjs/cli/node_modules/chokidar/node_modules/fsevents):
```
I was then unable to start the container because I receieved this error:
```
Error: ENOENT: no such file or directory, open '/app/.env'
```

2021-07-13 04:34 UTC, xthursdayx commented on docker/docker-compose.yml
> +      - NODE_ENV=development
This is where @cromefire mentioned that: https://github.com/getferdi/server/pull/48/files#r666683019

2021-07-13 04:42 UTC, xthursdayx commented
> > you can for his branch and open a new PR from that one and close this.
> 
> Yes, I know that - but, don't want to hijack his work and plagiarize it. imo, its better for @xthursdayx to fix it.

Well, its all of our work, specifically much of it being work done by @cromefire @k0staa and myself, so I care more about us getting it merged than the idea of anything being plagiarized, since it's a collaborative effort. 

> @xthursdayx @cromefire - are you folks ready to merge the PR now? Looks like this branch still has conflicts.
> <img alt="Screenshot 2021-07-13 at 4 54 02 AM" width="947" src="https://user-images.githubusercontent.com/69629/125367744-5bd1ae80-e396-11eb-93f5-779d5116c5a6.png">

You don't need to screenshot the change requests, I can see them as well. I'm currently working on addressing some of the remaining things we've discussed and then I think it should be ready.

> Is the migration path tested? That should probably happen before merging too

I just tried building a container with the existing docker image and a new image based on @k0staa 's branch. I ran into an error that relates to `/app/.env`: `Error: ENOENT: no such file or directory, open '/app/.env'`. I have a sense that this might have to do with line 30 in `entrypoint.sh`: 	`APP_KEY=$(grep APP_KEY .env | cut -d '=' -f2)`

I detailed the errors here:
https://github.com/getferdi/server/pull/48/files/a347c97e6b1efb344752951af5db81d84e91e58f#r668416567

Any idea what is causing the issue @cromefire ?

Also, could you all check the other changes I committed this even and see if they make sense: https://github.com/getferdi/server/blob/68b5c7a287afde31880436b8ea496fa70202fa6d/config/database.js

2021-07-13 07:46 UTC, cromefire commented
Nope, `EOENT` is a JS error, but I think a `.env` is required, so just create an empty one in the `Dockerfile`

2021-07-13 07:52 UTC, cromefire commented on docker/docker-compose.yml
> +      - NODE_ENV=development
Uh this is a different thing, but try it and see if it runs using `production` I guess?

2021-07-13 07:54 UTC, cromefire commented on docker/.gitignore
> +# Node modules
Well I don't care, I use nested ignore files more often, because the allow you to categorize stuff, but it won't kill ya not doing it.

2021-07-13 09:16 UTC, cromefire commented on docker/entrypoint.sh
> +if [ ! -f "/config/FERDI_APP_KEY.txt" ];
Also shouldn't we check here that the `APP_KEY` env isn't already set? Do we even want to keep this generation or do we just want everyone to generate one manually and setting it in the compose file or what ever you use (I guess we probably could provide a command to generate it or something like that).

2021-07-13 09:27 UTC, xthursdayx commented
> Please see my outstanding comments

Turns out that that `path.join` command you suggested including isn't working, do you have any suggestions for fixing it? This is my container error message at startup:
```
ReferenceError: path is not defined

at /app/config/database.js(anonymous):34
29 |
30 */
31 sqlite: {
32 client: 'sqlite3',
33 connection: {
34 filename: path.join(Env.get('DATA_DIR', 'data'), `${Env.get('DB_DATABASE', 'ferdi')}.sqlite`),
35 },
36 useNullAsDefault: true,
37 debug: Env.get('DB_DEBUG', false),
38 },
39

1 anonymous
/app/node_modules/require-all/index.js:56

2 requireAll
/app/node_modules/require-all/index.js:34

```

2021-07-13 09:30 UTC, cromefire commented
You have to import the path library, in plain node.js you'd do it like this:
```javascript
const path = require("path");
```

2021-07-13 09:32 UTC, xthursdayx commented on docker/docker-compose.yml
> +      - NODE_ENV=development
I'll try it out in my test build once we sort out the `path.join` issue below.

2021-07-13 09:33 UTC, cromefire commented on docker/entrypoint.sh
> +if [ ! -f "/config/FERDI_APP_KEY.txt" ];
Well there's not much more we can do in terms of persistence, but we could move it to the `DATA_DIR` path, because that should be a volume anyway.

2021-07-13 09:35 UTC, cromefire commented
It doesn't have anything to do with Adonis, it's just plain node.js there

2021-07-13 09:37 UTC, cromefire commented
Also now that I start to think about it, for docker only should we change the default `DATA_DIR` to `/data`? That's no good default for non docker, but in docker you usually mount you volumes to the root dir.

2021-07-13 09:48 UTC, xthursdayx commented
> Also now that I start to think about it, for docker only should we change the default `DATA_DIR` to `/data`? That's no good default for non docker, but in docker you usually mount you volumes to the root dir.

I'd had the same thought, but I pretty much only work on Docker containers, so that's what I'm used to. I'd tend to go for `/data`, but I don't know how that would impact people in non-Docker and/or non-Linux environments.

2021-07-13 09:51 UTC, xthursdayx commented on docker/entrypoint.sh
> +if [ ! -f "/config/FERDI_APP_KEY.txt" ];
When I wrote the original code only `/config` was a host-mounted volume. However I think now `/config`, `/app/recipes` and `/app/data` are all persistent volumes if I'm not mistaken, so it can probably stay in `/config`, no?

2021-07-13 10:07 UTC, cromefire commented on docker/entrypoint.sh
> +if [ ! -f "/config/FERDI_APP_KEY.txt" ];
Well it's not containing configs anymore, right?

2021-07-13 10:08 UTC, cromefire commented on docker/entrypoint.sh
> +if [ ! -f "/config/FERDI_APP_KEY.txt" ];
I'd just have `/data` and `/recipes`, I guess that makes more sense, as the key is application generated.

2021-07-13 10:10 UTC, cromefire commented
Well we can just set a different default for docker. For normal Linux this would be a no-go.

2021-07-13 11:18 UTC, xthursdayx commented
> Well we can just set a different default for docker (using `ENV` in the dockerfile and the example docker compose). For normal Linux this would be a no-go.

Should it be /data or /app/data? Or I guess you're suggesting no /app directory at all. Does the Dockerfile you wrote not use /app at all?

2021-07-13 11:29 UTC, xthursdayx commented
I'm working on updating all of the `data_dir` references in the container code to `/data` but you mentioned (in a comment I can't seem to find) just having the directories `/data/ and `/recipes`, but isn't `/recipes` inside `/app` or is there a way to change its location?

2021-07-13 11:30 UTC, cromefire commented
I'm not sure if you can change it's location, if not this would of course be a good fit for the upgrade.

2021-07-13 11:32 UTC, cromefire commented
> > Well we can just set a different default for docker (using `ENV` in the dockerfile and the example docker compose). For normal Linux this would be a no-go.
> 
> Should it be /data or /app/data? Or I guess you're suggesting no /app directory at all. Does the Dockerfile you wrote not use /app at all?

No I was just thinking for docker (as opposed to the rest) it'd be good to move the data folder from the app dir and put it into the root dir, so you don't have to have it nested.

2021-07-13 11:33 UTC, vraravam approved these changes

2021-07-13 11:33 UTC, vraravam commented on docker/docker-compose.yml
> +      - NODE_ENV=development
I dont see any outstanding comments related to `path.join` - was that fixed?

2021-07-13 11:35 UTC, xthursdayx commented on docker/docker-compose.yml
> +      - NODE_ENV=development
I added the code the @cromefire suggested, but haven't tested it yet. You're welcome to if you'd like.

2021-07-13 11:36 UTC, cromefire requested changes

2021-07-13 11:36 UTC, cromefire commented on config/database.js
> +      filename: path.join(Env.get('DATA_DIR', '/data'), `${Env.get('DB_DATABASE', 'ferdi')}.sqlite`),
`/data` should only be the default for docker, not the entire app

2021-07-13 11:43 UTC, cromefire requested changes

2021-07-13 11:43 UTC, cromefire commented on .env.example
> +DATA_DIR=/data
Same here the example file isn't docker related.

2021-07-13 11:43 UTC, cromefire commented on Dockerfile
> +ENV HOST=0.0.0.0 PORT=3333
```suggestion
ENV HOST=0.0.0.0 PORT=3333 DATA_DIR="/data"
```

2021-07-13 11:43 UTC, cromefire commented on docker/README.md
> +	  -e DATA_DIR=data \
```suggestion
	  -e DATA_DIR=/data \
```

2021-07-13 11:43 UTC, cromefire commented on docker/docker-compose.yml
> +      - DATA_DIR=data # existing Ferdi-server users should ensure that they add this variable to ensure data persistence.
```suggestion
      - DATA_DIR=/data # existing Ferdi-server users should ensure that they add this variable to ensure data persistence.
```

2021-07-13 11:43 UTC, cromefire commented on docker/entrypoint.sh
> +if  [[ -f "/app/adata/FERDI_APP_KEY.txt" ]]; then
```suggestion
if  [[ -f "${DATA_DIR}/FERDI_APP_KEY.txt" ]]; then
```

2021-07-13 11:43 UTC, cromefire commented on docker/entrypoint.sh
> +	echo $APP_KEY > /app/data/FERDI_APP_KEY.txt
```suggestion
	echo "${APP_KEY}" > "${DATA_DIR}/FERDI_APP_KEY.txt"
```

2021-07-13 11:54 UTC, cromefire requested changes

2021-07-13 11:54 UTC, cromefire commented on docker/README.md
> +	  -p <port>:80 \
If I remember correctly the port is 3333 by default, right?

```suggestion
	  -p <port>:3333 \
```

2021-07-13 11:54 UTC, cromefire commented on docker/README.md
> +	  -v <path to recipes>:/app/recipes \
```suggestion
	  -v <path to data>:/data \
	  -v <path to recipes>:/app/recipes \
```

2021-07-13 11:54 UTC, cromefire commented on docker/README.md
> +| `-v <path to recipes>:/app/recipes` | this will store Ferdi-server's recipes on the docker host for persistence |
```suggestion
| `-v <path to data>:/data` | this will store Ferdi-server's data (among others the database) on the docker host for persistence. See the [Docker docs](https://docs.docker.com/storage/volumes/) for more information on the use of container volumes |
| `-v <path to recipes>:/app/recipes` | this will store Ferdi-server's recipes on the docker host for persistence |
```

2021-07-13 12:02 UTC, xthursdayx commented on config/database.js
> +      filename: path.join(Env.get('DATA_DIR', '/data'), `${Env.get('DB_DATABASE', 'ferdi')}.sqlite`),
What do you think the best way is to separate the two? Just by requiring Docker users to enter the `DATA_DIR` variable?

2021-07-13 12:04 UTC, cromefire commented on config/database.js
> +      filename: path.join(Env.get('DATA_DIR', '/data'), `${Env.get('DB_DATABASE', 'ferdi')}.sqlite`),
No, as commented (I left you some suggestions) just set those in the Dockerfile and the docs/example compose file

2021-07-13 12:06 UTC, xthursdayx commented on config/database.js
> +      filename: path.join(Env.get('DATA_DIR', '/data'), `${Env.get('DB_DATABASE', 'ferdi')}.sqlite`),
Done.

2021-07-13 12:10 UTC, cromefire commented
I guess it's fine then, but I'll probably have to check this on the PC again, as I've done almost all review here on my phone, which isn't the greatest tool for that.

2021-07-13 13:15 UTC, xthursdayx commented on docker/docker-compose.yml
> +      - NODE_ENV=development
Testing now and running into issues, but I'll report back soon.

2021-07-17 13:38 UTC, vraravam commented
@cromefire - is this ready for merge? were you able to test the changes in this PR?

2021-07-17 13:39 UTC, cromefire commented
No i was not, I'll try to get that done in a few mins

2021-07-17 15:00 UTC, cromefire requested changes
Looks fine, aside from some better documentation of the migration path. Everything else _looks_ okay.

2021-07-17 21:55 UTC, xthursdayx commented
I had a very busy work week so hadn't finished making all the changes I'd planned to, and so hadn't tested the final version. 

I can check on the state of things later tonight or tomorrow and hopefully merge if it's ready. 

I'll check on the documentation as well. I thought I'd updated most of it, but some of that may have been on my "To do" list rather than my "Done" list. Let me know if you have any suggestions for where there are holes or for any additions/rewrites/etc @cromefire and I'll add them.

I will also try to make some time to do a test build of the new image and a migration from the an existing container to the new version to make sure everything works. It may have to be tomorrow though.

2021-07-18 10:04 UTC, xthursdayx commented
Okay, since I've been focusing on the migration dimension of this change, I built a container using the current image's default values and built-in sqlite database - this worked fine (as we already knew) and I made an account via Ferdi connected to my locally running server. 

I then tried to migrate this existing to container (and the built-in sqlite db) to a new container pulled from an up-to-date local build of the new image (from @k0staa ) using the migration instructions @cromefire and I worked on. This immediately created an error in the log stating that `/app/.env` was unable to be found (mirroring the error we came across previously with the new image stating that "no `.env` file could be found at `/data`" (despite this file not being needed in the new image).

I then updated the Dockerfile to add the empty `/.env` file to `/app` instead of `/data`, locally rebuilt the image, and ran the container again. The result is that the Docker log looks fine:
```
**** App Key found ****
**** App Key set to you can modify FERDI_APP_KEY.txt to update your key ****
[36mNothing to migrate[39m
[32minfo[39m: serving app on http://0.0.0.0:3333
```
(No NPM errors! YAY)

But when I visit the local instance of Ferdi server running at my http://<myserverip>:3333 I get an html page with the following error:
```
RuntimeException: E_MISSING_APP_KEY: Make sure to define appKey inside config/app.js file before using Encryption provider
> More details: https://err.sh/adonisjs/errors/E_MISSING_APP_KEY
RuntimeException: E_MISSING_APP_KEY: Make sure to define appKey inside config/app.js file before using Encryption provider
> More details: https://err.sh/adonisjs/errors/E_MISSING_APP_KEY
    at Function.missingAppKey (/app/node_modules/@adonisjs/generic-exceptions/src/RuntimeException.js:54:12)
    at new Encryption (/app/node_modules/@adonisjs/framework/src/Encryption/index.js:33:33)
    at Object.closure (/app/node_modules/@adonisjs/framework/providers/AppProvider.js:257:14)
    at Ioc._resolveBinding (/app/node_modules/@adonisjs/fold/src/Ioc/index.js:231:68)
    at Ioc.make (/app/node_modules/@adonisjs/fold/src/Ioc/index.js:807:19)
    at /app/node_modules/@adonisjs/fold/src/Ioc/index.js:318:19
    at Array.map (<anonymous>)
    at Ioc._makeInstanceOf (/app/node_modules/@adonisjs/fold/src/Ioc/index.js:317:44)
    at Ioc.make (/app/node_modules/@adonisjs/fold/src/Ioc/index.js:799:19)
    at AuthManager.getScheme (/app/node_modules/@adonisjs/auth/src/Auth/Manager.js:86:16)
    at Auth.authenticator (/app/node_modules/@adonisjs/auth/src/Auth/index.js:118:40)
    at new Auth (/app/node_modules/@adonisjs/auth/src/Auth/index.js:68:39)
    at Context.<anonymous> (/app/node_modules/@adonisjs/auth/providers/AuthProvider.js:151:14)
    at Context.wrappedCallback [as auth] (/app/node_modules/macroable/index.js:132:61)
    at Server._handleException (/app/node_modules/@adonisjs/framework/src/Server/index.js:253:63)
    at /app/node_modules/@adonisjs/framework/src/Server/index.js:441:14
```
I then finally tried migrating  my actual Ferdi-server instance (well, a copy of it), which uses an external MariaDB database rather than the built-in sqlite db. Because of this, I only updated the container port from 80 to 3333, but kept my other existing variables and mappings. I did not add the `DATA_DIR` variable, since I am not using the built in sqlite db and didn't' think it was necessary in that case. *Note* It is actually necessary given the way the entrypoint.sh script is currently written. I also didn't revert the Dockerfile to copy the empty `.env` file to `/data` rather than `/app`. Trying to run the server then resulted in this in this error:

```
**** Generating Ferdi-server app key for first run ****
[32mgenerated:[39m unique APP_KEY
/entrypoint.sh: line 27: can't create /data/FERDI_APP_KEY.txt: nonexistent directory
**** App Key set to WOWrWgd8LbiQneHr7dXT6Qmq81VeiRik you can modify FERDI_APP_KEY.txt to update your key ****

n
$ npm install mysql --save
Error: Cannot find module 'mysql'

Require stack:
- /app/node_modules/knex/lib/dialects/mysql/index.js
- /app/node_modules/knex/lib/index.js
- /app/node_modules/knex/knex.js
- /app/node_modules/@adonisjs/lucid/src/Database/index.js
- /app/node_modules/@adonisjs/lucid/src/Database/Manager.js
- /app/node_modules/@adonisjs/lucid/providers/LucidProvider.js
- /app/node_modules/require-stack/src/index.js
- /app/node_modules/require-stack/index.js
- /app/node_modules/@adonisjs/fold/src/Ioc/index.js
- /app/node_modules/@adonisjs/fold/index.js
- /app/ace
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
at Function.Module._load (internal/modules/cjs/loader.js:746:27)
at Module.require (internal/modules/cjs/loader.js:974:19)
at require (internal/modules/cjs/helpers.js:92:18)
at Client_MySQL._driver (/app/node_modules/knex/lib/dialects/mysql/index.js:59:12)
at Client_MySQL.initializeDriver (/app/node_modules/knex/lib/client.js:250:26)
at Client_MySQL.Client (/app/node_modules/knex/lib/client.js:108:10)
at new Client_MySQL (/app/node_modules/knex/lib/dialects/mysql/index.js:49:20)
at Knex (/app/node_modules/knex/lib/index.js:56:34)
at new Database (/app/node_modules/@adonisjs/lucid/src/Database/index.js:80:17)
at DatabaseManager.connection (/app/node_modules/@adonisjs/lucid/src/Database/Manager.js:81:35)
at Object.get (/app/node_modules/@adonisjs/lucid/lib/proxyGet.js:40:77)
at Migration._makeMigrationsTable (/app/node_modules/@adonisjs/lucid/src/Migration/index.js:47:36)
at Migration.up (/app/node_modules/@adonisjs/lucid/src/Migration/index.js:336:16)
at MigrationRun.handle (/app/node_modules/@adonisjs/lucid/commands/MigrationRun.js:72:66)
at /app/node_modules/@adonisjs/ace/src/Command/index.js:565:48
[32minfo[39m: serving app on http://0.0.0.0:3333
```

Finally I rebuilt the container and included the `DATA_DIR` variable mapped to my legacy `/app/data` volume, but this still resulted in the same error:
```
**** Generating Ferdi-server app key for first run ****
[32mgenerated:[39m unique APP_KEY
**** App Key set to GwZUigJZVg94qubLXVYQF6mndLUZEb72 you can modify FERDI_APP_KEY.txt to update your key ****

n
$ npm install mysql --save
Error: Cannot find module 'mysql'

Require stack:
- /app/node_modules/knex/lib/dialects/mysql/index.js
- /app/node_modules/knex/lib/index.js
- /app/node_modules/knex/knex.js
- /app/node_modules/@adonisjs/lucid/src/Database/index.js
- /app/node_modules/@adonisjs/lucid/src/Database/Manager.js
- /app/node_modules/@adonisjs/lucid/providers/LucidProvider.js
- /app/node_modules/require-stack/src/index.js
- /app/node_modules/require-stack/index.js
- /app/node_modules/@adonisjs/fold/src/Ioc/index.js
- /app/node_modules/@adonisjs/fold/index.js
- /app/ace
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
at Function.Module._load (internal/modules/cjs/loader.js:746:27)
at Module.require (internal/modules/cjs/loader.js:974:19)
at require (internal/modules/cjs/helpers.js:92:18)
at Client_MySQL._driver (/app/node_modules/knex/lib/dialects/mysql/index.js:59:12)
at Client_MySQL.initializeDriver (/app/node_modules/knex/lib/client.js:250:26)
at Client_MySQL.Client (/app/node_modules/knex/lib/client.js:108:10)
at new Client_MySQL (/app/node_modules/knex/lib/dialects/mysql/index.js:49:20)
at Knex (/app/node_modules/knex/lib/index.js:56:34)
at new Database (/app/node_modules/@adonisjs/lucid/src/Database/index.js:80:17)
at DatabaseManager.connection (/app/node_modules/@adonisjs/lucid/src/Database/Manager.js:81:35)
at Object.get (/app/node_modules/@adonisjs/lucid/lib/proxyGet.js:40:77)
at Migration._makeMigrationsTable (/app/node_modules/@adonisjs/lucid/src/Migration/index.js:47:36)
at Migration.up (/app/node_modules/@adonisjs/lucid/src/Migration/index.js:336:16)
at MigrationRun.handle (/app/node_modules/@adonisjs/lucid/commands/MigrationRun.js:72:66)
at /app/node_modules/@adonisjs/ace/src/Command/index.js:565:48
[32minfo[39m: serving app on http://0.0.0.0:3333
```

Any [...]

2021-07-18 10:17 UTC, xthursdayx commented
By the way, I was using Docker-CLI (docker build and docked run) with these builds, not Compose, so didn't use the 'docker-compose.yml' file, and was just passing the variables manually in the run command, if that matters at all.

2021-07-18 20:32 UTC, xthursdayx commented
Okay, I figured out that the issue is that the `.dockerignore` still includes `node_modules`, due to the way that the previous (currently published) Docker image installed Ferdi-server at start-up. I will try removing this and running it to see if this work and if it has any additional negative impacts.

2021-07-19 01:44 UTC, vraravam commented
> Okay, I figured out that the issue is that the `.dockerignore` still includes `node_modules`, due to the way that the previous (currently published) Docker image installed Ferdi-server at start-up. I will try removing this and running it to see if this work and if it has any additional negative impacts.

@xthursdayx : I'm not sure I completely understand why this would cause any issues. Including the `node_modules` in the Docker context is typically not a good thing, correct?

2021-07-19 07:47 UTC, xthursdayx commented
> > Okay, I figured out that the issue is that the `.dockerignore` still includes `node_modules`, due to the way that the previous (currently published) Docker image installed Ferdi-server at start-up. I will try removing this and running it to see if this work and if it has any additional negative impacts.
> 
> @xthursdayx : I'm not sure I completely understand why this would cause any issues. Including the `node_modules` in the Docker context is typically not a good thing, correct?

It was just a though t I had in passing and haven't tested yet. I agree, it's not a good thing, but based on the errors I included above it appears that the necessary node-modules are missing and I'm not sure what has changed in the docker image update to cause that. Now that I've look more closely at things, I think I'm probably incorrect.

My assumption is that the missing modules are a due to the change in the way that `npm` and `adonis/cli` are added in the new Dockerfile. 

Previously my s6 runtime script ran the following commands from within the `/app` directory (after pulling the server repo to that directory in the Dockerfile).
```
npm config set unsafe-perm true 
npm i -g @adonisjs/cli 
npm install # to install the adonis dependencies
```
Whereas the new [Dockerfile](https://github.com/k0staa/server/blob/master/Dockerfile) now only includes the line `RUN ["npm", "i", "-g", "@adonisjs/cli"]`, but nothing that seems to install the adonis dependencies, and the new `entrypoint.sh` doesn't install these dependencies either. So, I think that the missing adonis dependencies are the main problem. But this just a guess since I didn't write the new Dockerfile or entrypoint script and I don't really know Node.

However, my guess could be totally wrong if, as it seems, `line 9` in the new [Dockerfile](https://github.com/k0staa/server/blob/master/Dockerfile) - `RUN ["npm", "ci", "--production", "--build-from-source", "--sqlite=/usr/local"]` builds Ferdi-server from the source root (where the Dockerfile is also located) and in the process installs ` the adonis dependencies, effecting nullifying the need for the `npm install` that I used my original s6 script. Again, because of my lack of knowledge, I'm not sure what the difference is between running `npm install` from within the `/app` directory at runtime AFTER installing `adonis/cli` and setting `unsafe-perm` to true in the npm config, versus using `npm` to build ferdi-server from the git source in the Dockerfile BEFORE using `npm` to install `@adonis/clii` in a later docker build stage, other than the fact that it avoids installing the server on the fly each time the container is started and therefore makes it start much faster. I'm not sure how the methods differ in terms of installing adonis' dependencies though and whether or not these dependencies persist across the different build stages in the new Dockerfile.  Any thoughts @cromefire ?

2021-07-20 12:08 UTC, cromefire commented
So regarding the `.env` error 2 steps:
1. Make sure that a `.env` exists in `/app`
2. Make sure the `WORKDIR` in the `Dockerfile` is set to `/app`

2021-07-20 12:18 UTC, cromefire commented
For mysql we should probably just add it to the `package.json`

2021-07-20 22:48 UTC, xthursdayx commented
> So regarding the `.env` error 2 steps:
> 
> 1. Make sure that a `.env` exists in `/app`
> 2. Make sure the `WORKDIR` in the `Dockerfile` is set to `/app`

I'd already added a line to the Dockerfile to copy an empty `.env` file into `/app` and you already had `WORKDIR` set to `/app` previously. 

> For mysql (and postgres) we should probably just add it to the `package.json`
Oddly both postgres (as `pg`) and `sqlite3` are already in the `package.json` as dependencies, but `mysql` is not. It makes sense to me why `sqlite` is already included since it is the default built-in database, but not `pg`, since postgres isn't a default. This seems to be a hold over from the original fork from Franz, as `pq` and `sqlite3` are included in the `package.json` in the [initial commit](https://github.com/getferdi/server/commit/b018adf240679ec59a7344e30be39400f1ecd8af#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) when Ferdi-server was forked from Franz, but I'm not sure what else, if anything, is using the `pg` client module. 

Anyway, `mysql` does appear in [`database.js`](https://github.com/getferdi/server/blob/master/config/database.js) as one of the option associated with the `DB_CONNECTION` environmental variable. In my previous version of the docker image I dealt with this issue by installing the db helper on the fly using the `DB_CONNECTION` env variable with these lines in an s6 cont.init config script: 
```
# setting the database helper
if [ "${DB_CONNECTION}" = "sqlite" ]; then
	echo " "
    echo "**** DB helper loaded ****"
  else npm i ${DB_CONNECTION} 
  echo " "
  echo "**** DB Helper loaded ****"
fi
```

"mysql": "^2.16.0",
I guess the question now is whether we want to add a similar check to the new `entrypoint.sh` script, or whether we want to add mysql as a default dependency in the `package.json`. 

AI can add `mysql` to the `package.json`, but one thing I just noticed relates to the installed package versions. As we know, all of the installed adonis deps that Ferdi-server relies on are far out of date, including `sqlite3` and `pg`, as well as `lucid` (the database driver). However, while the `package.json` calls for `"@adonisjs/lucid": "^6.1.3"` it also calls for `"pg": "^7.18.2"` and `"sqlite3": "^4.1.0"`. This is the same version of `sqlite3` that was in the original fork from Franz, however it is not the same version as that listed by `lucid:v6.1.3`, which is `"sqlite3": "^4.0.2"`. Moreover, the `pg` dep listed in the `package.json` was more recently updated as part of this commit: https://github.com/getferdi/server/commit/9cbe1174b23922e86a2c25de8506d4468cd4511e#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519 though I'm not sure why. Perhaps @vantezzen knows if something else is using the pg dep?

2021-07-21 07:08 UTC, cromefire commented
> > So regarding the `.env` error 2 steps:
> > 
> > 1. Make sure that a `.env` exists in `/app`
> > 2. Make sure the `WORKDIR` in the `Dockerfile` is set to `/app`
> 
> I already added a line to the Dockerfile to copy an empty `.env` file into `/app` and you or @k0staa had already set `WORKDIR` to `/app` in the final stage of the Dockerfile. 

Hmm then I'm not sure how to fix it, it somehow searches inside `/data` and not inside `/app`.

> > For mysql (and postgres) we should probably just add it to the `package.json`
> 
> Oddly both postgres (as `pg`) and `sqlite3` are already in the `package.json` as dependencies, but `mysql` is not. It makes sense to me why `sqlite3` is included, since it is the default built-in database, but not `pg`, since postgres isn't a default. This seems to be a hold over from the original fork from Franz, as `pq` and `sqlite3` are included in the `package.json` in the [initial commit](https://github.com/getferdi/server/commit/b018adf240679ec59a7344e30be39400f1ecd8af#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519), but I'm not sure what else, if anything, is using the `pg` client module. 
> 
> Anyway, `mysql` does appear in [`database.js`](https://github.com/getferdi/server/blob/master/config/database.js) as one of the options associated with the `DB_CONNECTION` environmental variable. In my previous version of the docker image I dealt with this issue by installing the db helper on the fly using the `DB_CONNECTION` env variable with these lines in an s6 cont.init config script: 
> ```
> # setting the database helper
> if [ "${DB_CONNECTION}" = "sqlite" ]; then
> 	echo " "
>     echo "**** DB helper loaded ****"
>   else npm i ${DB_CONNECTION} 
>   echo " "
>   echo "**** DB Helper loaded ****"
> fi
> ```

Just add it using `npm install --save <dependency>`

> I guess the question now is whether we want to add a similar check to the new `entrypoint.sh` script, or whether we want to add mysql as a default dependency in the `package.json`. Any thoughts @cromefire , since you and @k0staa wrote the `entrypoint.sh` and new version of the Dockerfile? My inclination would be to agree with what you suggested above and add it to the `package.json` and `package-lock.json`, however I don't know how the package-lock.json file is generated, so if you or anyone else can help with that it would be great.

It's generated.

> I can add `mysql` to the `package.json`, but one thing I just noticed relates to the installed package versions. As we know, all of the installed adonis deps that Ferdi-server relies on are far out of date, including `sqlite3` and `pg`, as well as `lucid` (the database driver). However, while the `package.json` calls for `"@adonisjs/lucid": "^6.1.3"` it also calls for `"pg": "^7.18.2"` and `"sqlite3": "^4.1.0"`. This is the same version of `sqlite3` that was in the original fork from Franz, however it is not the same version as that listed in the `package.json` for `lucid:v6.1.3`, which is `"sqlite3": "^4.0.2"`. Moreover, the `pg` dep listed in the Ferdi-server `package.json` was more recently updated as part of commit https://github.com/getferdi/server/commit/9cbe1174b23922e86a2c25de8506d4468cd4511e to `v.7.18.2`, though I'm not sure why, and the `pg` dep listed for `lucid:6.1.3` is `v7.4.3`. Perhaps @vantezzen knows if something else is using `pg`?
> 
> The question is if we dp add `mysql` to the `package.json` and `package-lock.json`, which version should we add? The version listed in `lucid:6.1.3`'s dependences is `"mysql": "^2.16.0"`, so should we use that one or a later version?

Maybe just be sure and use the version known to work.

2021-07-21 09:20 UTC, xthursdayx commented on Dockerfile
> +# TODO:  implement process to run ferdi-server as non-root user. See comments on https://github.com/getferdi/server/pull/48/
I believe that I've addressed this by running the server with su-exec.

2021-07-21 10:18 UTC, xthursdayx commented
> > I already added a line to the Dockerfile to copy an empty `.env` file into `/app` and you or @k0staa had already set `WORKDIR` to `/app` in the final stage of the Dockerfile.
> 
> Hmm then I'm not sure how to fix it, it somehow searches inside `/data` and not inside `/app`.
> 
> > > For mysql (and postgres) we should probably just add it to the `package.json`
> 
> Just add it using `npm install --save <dependency>`
> 
> > The question is if we dp add `mysql` to the `package.json` and `package-lock.json`, which version should we add? The version listed in `lucid:6.1.3`'s dependences is `"mysql": "^2.16.0"`, so should we use that one or a later version?
> 
> Maybe just be sure and use the version known to work.

Unfortunately, I didn't see your response before I sorted this out, but anyway, it all seems to be working. I've added mysql to the `package.json` and updated the `package-lock.json`. I have since tested the image both as a fresh install, using the internal `sqlite3` database, and have tested migrating an existing ferdi-server that uses an external MariaDB database. Both worked without any errors (other than the many depreciation warnings for all of the adonis components while building the container). 

If you all think that the documentation for migrating from an existing server is I believe sufficient then I think that this PR is ready to be merged. However, it would be great if anyone else would be willing to test the PR version of the image to ensure that it is indeed working as expected. Once that happens I'll merge the PR.

2021-07-21 10:22 UTC, xthursdayx commented on docker/docker-compose.yml
> +      - NODE_ENV=development
Just to update, `path.join` was fixed. I am leaving the Node environment as is for now, since there are still a lot of underlying issues with Adonis and it's associated components that need to be addressed. In the mean time the new version of the docker is working well both from fresh install and when migrating from an existing container.

2021-07-21 10:24 UTC, xthursdayx approved these changes

2021-07-26 09:06 UTC, xthursdayx commented
Has anyone had a chance to test new image (both/either as an original build or while migrating from an existing server? It'd be great to geet some more testing done so that we can merge this PR and more on to working on developing our Docker image workflow build process. Cheers.

2021-08-20 22:42 UTC, xthursdayx commented
Alright folks, it's been about a month now. I don't know if anyone has tested the new version out or not, but I've been using it without an issue with the new variables. I'm happy to merge this PR before it falls too far behind the base and get rid of the server-docker repo, so please let me know if you have any objections to this (@vantezzen @kytwb).

Once merged, we will need to put into place a GitHub workflow to test and publish the image to Docker Hub, and ideally make the image multi-arch.

2021-08-20 22:54 UTC, cromefire commented
Probably fine, I mean one could probably a beta or something along those lines, I sadly can't test it in the next weeks as I'm very busy current.

2021-08-24 02:24 UTC, vraravam commented on docker/entrypoint.sh
> +	APP_KEY=$(cat /data/FERDI_APP_KEY.txt)
Should we use the `${DATA_DIR}` env var here since that's used on line 18?

2021-08-24 02:28 UTC, vraravam commented on docker/entrypoint.sh
> +elif [[ -z "${APP_KEY}" ]]; then
Instead of an `if-else-if`, imo its better to separate the two into a single `if` where the check becomes `if env var is not set, and if file is not present, then generate and set the file`. This can be followed by `read from file` (since the file will always be present). Isn't that better?

2021-08-24 02:29 UTC, vraravam commented on docker/docker-compose.yml
> +  ferdi-server:
Since we are running docker-compose, can we not run the `mysql` db as well in a container (as opposed to it being used as a system dependency?

2021-08-24 07:36 UTC, cromefire commented on docker/docker-compose.yml
> +  ferdi-server:
We don't have it as a system dependency, the default is SQLite. But yes you can use MySQL in a neighboring container.

2021-08-24 07:38 UTC, cromefire commented on docker/entrypoint.sh
> +	APP_KEY=$(cat /data/FERDI_APP_KEY.txt)
Yes

2021-09-16 21:53 UTC, xthursdayx commented on docker/entrypoint.sh
> +elif [[ -z "${APP_KEY}" ]]; then
I'm not sure that I fully follow why that would be better. Wouldn't that just switch the process around aniit rather than really simplfy it? I could be totally wrong. Is something like this what you were envisioning @vraravam :
```
if [[ -z ${APP_KEY} && ! -f "${DATA_DIR}/FERDI_APP_KEY.txt" ]]; then
	echo "**** Generating Ferdi-server app key for first run ****"
	adonis key:generate
	APP_KEY=$(grep APP_KEY .env | cut -d '=' -f2)
	echo "${APP_KEY}" > "${DATA_DIR}/FERDI_APP_KEY.txt"
	echo "**** App Key set to $APP_KEY you can modify FERDI_APP_KEY.txt to update your key ****"
else APP_KEY=$(cat "${DATA_DIR}/FERDI_APP_KEY.txt")
	echo "**** App Key set to $APP_KEY you can modify FERDI_APP_KEY.txt to update your key ****"
fi
```

2021-09-16 22:00 UTC, xthursdayx commented on docker/docker-compose.yml
> +  ferdi-server:
I agree, we could add MySQL to the docker-compose, but as @cromefire says, the default db is SQLite, which is included in the main image. In general, I that I prefer the freedom of allowing the user to choose whether or not they want run an external database container (whether MySQL or PostgreSQL), rather than building it into the docker-compose.

2021-09-16 22:16 UTC, xthursdayx commented on docker/entrypoint.sh
> +elif [[ -z "${APP_KEY}" ]]; then
I'm happy to subsitute that if you think it's better, there are a couple of other edits that need to be made anyway, as I just realized that the script shebang is `/bin/sh` but `[[` is Bash-specific and not POSIX compatible, so either the shebang or the script needs to be changed. I've rewritten it like this, if the above `if` statement is what you had in mind:
```
#!/bin/bash

cat << EOL
-------------------------------------
          ____           ___
         / __/__ _______/ (_)
        / _// -_) __/ _  / /
      _/_/  \__/_/  \_,_/_/
     / __/__ _____  _____ ____
    _\ \/ -_) __/ |/ / -_) __/
   /___/\__/_/  |___/\__/_/
Brought to you by getferdi.com
Support our Open Collective at:
https://opencollective.com/getferdi/
EOL

# Create APP key if needed
if [[ -z ${APP_KEY} && ! -f "${DATA_DIR}/FERDI_APP_KEY.txt" ]]; then
	echo "**** Generating Ferdi-server app key for first run ****"
	adonis key:generate
	APP_KEY=$(grep APP_KEY .env | cut -d '=' -f2)
	echo "${APP_KEY}" > "${DATA_DIR}/FERDI_APP_KEY.txt"
	echo "**** App Key set to $APP_KEY you can modify FERDI_APP_KEY.txt to update your key ****"
else APP_KEY=$(cat "${DATA_DIR}/FERDI_APP_KEY.txt")
	echo "**** App Key set to $APP_KEY you can modify FERDI_APP_KEY.txt to update your key ****"
fi

export APP_KEY

node ace migration:run --force

chown -R "${PUID:-1000}":"${PGID:-1000}" "$DATA_DIR" /app

su-exec "${PUID:-1000}":"${PGID:-1000}" node server.js#!/bin/bash
```

2021-09-17 03:05 UTC, vraravam requested changes

2021-09-17 03:05 UTC, vraravam commented on docker/README.md
> +       	# all ssl related config moved to ssl.conf
indentation

2021-09-17 03:05 UTC, vraravam commented on docker/docker-compose.yml
> +  ferdi-server:
I'm ok with sqlite being within (embedded) in the single docker image. What I was pointing out was: if the user wants to use mysql or something else that is not embedded, then, since we are using docker-compose anyways, we can leverage that capability.

2021-09-17 03:05 UTC, vraravam commented on docker/entrypoint.sh
> +elif [[ -z "${APP_KEY}" ]]; then
yes, this is simpler imo

2021-09-17 03:05 UTC, vraravam commented on package.json
> +    "mysql": "2.18.1",
Why do we need this if its an optional dependency?

2021-09-17 04:18 UTC, cromefire commented on docker/README.md
> +To use a different database than the default, SQLite3, enter the driver code below in your ENV configuration.
Nope, no need for anything OS, just change the env variable at least that seems to be working fine for PostgreSQL and I am quite sure it's the same for MySQL.

2021-09-17 04:21 UTC, cromefire commented on package.json
> +    "mysql": "2.18.1",
It's only using up a bit of image size, but it's way easier for users using the other DBs otherwise they'd need to install it themselves in the docker image and stuff like that, that's just a bit annoying for saving a few KB space.

2021-09-17 04:22 UTC, cromefire commented on docker/README.md
> +**Existing users, please note:** The latest updates to Ferdi-server and the Ferdi-server Docker image introduce changes to the default SQLite database name and location, as well as the internal conta
Well, that's the thing... There's no versions until now... It's all `latest`.

2021-09-17 08:36 UTC, xthursdayx commented on docker/README.md
> +**Existing users, please note:** The latest updates to Ferdi-server and the Ferdi-server Docker image introduce changes to the default SQLite database name and location, as well as the internal conta
That's part of the reason I want to get this merged soon, even as a beta/pre-release, in order to get proper versioning in place.

2021-09-17 10:23 UTC, xthursdayx commented on docker/README.md
> +       	# all ssl related config moved to ssl.conf
I believe this should be fixed now.

2021-09-17 10:28 UTC, vraravam approved these changes

2021-09-17 19:57 UTC, xthursdayx commented
Alright, unless anyone has any additional conccerns, I'm going to merge this PR later today. Let me know if there are any additional issues.

2021-09-18 06:21 UTC, merged