Add lastname column to User DB table and update API logic to save,update and return this data.
getferdi/server pull request #50
Opened 2021-02-06 19:12 UTC by k0staa

In order to fix issue [https://github.com/getferdi/ferdi/issues/1040](https://github.com/getferdi/ferdi/issues/1040) I updated `User` db table and added `lastname`. I changed the controllers to persist this field. I also updated all views where this data can be shown (data,account). 
To finalize the fix, I also added a pull request in the ferdi repository ->

2021-02-06 19:37 UTC, kytwb requested changes
Thanks! I left a minor review regarding the dashboard, the rest looks good to me.

2021-02-06 19:37 UTC, kytwb commented on resources/views/dashboard/data.edge
> +                  {{ workspace.lastname }}
This `td` and the corresponding `th` above have been added to the wrong section of the dashboard.

2021-02-07 09:14 UTC, k0staa commented on resources/views/dashboard/data.edge
> +                  {{ workspace.lastname }}
Shame on me ... I tried to be too fast. Fixed.
![2021-02-07-101051_1920x1080_scrot](https://user-images.githubusercontent.com/6313392/107142137-20394100-692d-11eb-985d-4d5a91873aae.png)

2021-02-07 09:57 UTC, kytwb commented on resources/views/dashboard/data.edge
> +                  {{ workspace.lastname }}
No shame, that's why we're doing the review.

2021-02-07 09:57 UTC, kytwb approved these changes

2021-02-07 09:58 UTC, merged